// AUTO-GENERATED by packages/ui-core/scripts/gen-icons-flutter.mjs — DO NOT EDIT.
// Regenerate: pnpm --filter @kungal/ui-core gen:icons:flutter

import 'package:flutter/widgets.dart';

const String _family = 'KunUiIcons';

/// Required for a font that ships inside a package: without it the family
/// resolves only within this package and every icon renders as tofu.
const String _package = 'kun_ui_icons';

/// The KunUI icon set.
///
/// The same icons the web components render, converted from lucide strokes
/// to filled glyphs and packed into the bundled `KunUiIcons` font. Use them
/// anywhere an `IconData` goes:
///
/// ```dart
/// Icon(KunIcons.circleCheck, size: 20)
/// ```
///
/// Codepoints are stable across releases: they are allocated once, in
/// `packages/ui-core/scripts/icon-codepoints.json`, and never reassigned.
abstract final class KunIcons {
  /// lucide: x
  static const IconData x = IconData(
    0xE000,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: check
  static const IconData check = IconData(
    0xE001,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: info
  static const IconData info = IconData(
    0xE002,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: circle-check
  static const IconData circleCheck = IconData(
    0xE003,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: circle-x
  static const IconData circleX = IconData(
    0xE004,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: triangle-alert
  static const IconData triangleAlert = IconData(
    0xE005,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: chevron-right
  static const IconData chevronRight = IconData(
    0xE006,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: chevron-left
  static const IconData chevronLeft = IconData(
    0xE007,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: chevron-down
  static const IconData chevronDown = IconData(
    0xE008,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: chevrons-right
  static const IconData chevronsRight = IconData(
    0xE009,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: chevrons-left
  static const IconData chevronsLeft = IconData(
    0xE00A,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: arrow-right
  static const IconData arrowRight = IconData(
    0xE00B,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: arrow-left
  static const IconData arrowLeft = IconData(
    0xE00C,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: plus
  static const IconData plus = IconData(
    0xE00D,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: minus
  static const IconData minus = IconData(
    0xE00E,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: upload
  static const IconData upload = IconData(
    0xE00F,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: zoom-in
  static const IconData zoomIn = IconData(
    0xE010,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: zoom-out
  static const IconData zoomOut = IconData(
    0xE011,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: rotate-cw
  static const IconData rotateCw = IconData(
    0xE012,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: rotate-ccw
  static const IconData rotateCcw = IconData(
    0xE013,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: refresh-ccw
  static const IconData refreshCcw = IconData(
    0xE014,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: external-link
  static const IconData externalLink = IconData(
    0xE015,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: download
  static const IconData download = IconData(
    0xE016,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: copy
  static const IconData copy = IconData(
    0xE017,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: calendar
  static const IconData calendar = IconData(
    0xE018,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: lollipop
  static const IconData lollipop = IconData(
    0xE019,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: eye
  static const IconData eye = IconData(
    0xE01A,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: eye-off
  static const IconData eyeOff = IconData(
    0xE01B,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: search
  static const IconData search = IconData(
    0xE01C,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: filter
  static const IconData filter = IconData(
    0xE01D,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: heart
  static const IconData heart = IconData(
    0xE01E,
    fontFamily: _family,
    fontPackage: _package,
  );

  /// lucide: heart, filled — the web's `fill-current` on it.
  static const IconData heartFilled = IconData(
    0xE01F,
    fontFamily: _family,
    fontPackage: _package,
  );
}

/// The bitmaps KunUI components draw without a network request.
///
/// The bytes the web components inline as data URIs, bundled here as
/// package assets; nothing needs declaring in your own `pubspec.yaml`:
///
/// ```dart
/// const Image(image: KunImages.nullImage, width: 250)
/// ```
abstract final class KunImages {
  /// KunNull's empty-state mascot, a 500×333 WebP (web `KUN_NULL_IMAGE`).
  static const AssetImage nullImage = AssetImage(
    'lib/images/null.webp',
    package: _package,
  );

  /// KunAvatar's last fallback, a 128×128 WebP (web `KUN_AVATAR_FALLBACK`):
  /// what renders when the app configured no avatar pool, or a pool image
  /// failed to load.
  static const AssetImage avatarFallback = AssetImage(
    'lib/images/avatar_fallback.webp',
    package: _package,
  );

  /// KunLoading's mascot, a 500×333 WebP (web `KUN_LOADING_IMAGE`).
  static const AssetImage loadingImage = AssetImage(
    'lib/images/loading.webp',
    package: _package,
  );
}
