// Extracts the exact SVG data for the finite set of icons KunUI components
// reference, from the locally-installed @iconify-json/* devDependencies, and
// writes them inline into src/icons-data.ts. The data is then BUNDLED — KunUI
// never fetches an icon at runtime.
//
// Add an icon: put its name in WANT below and run `pnpm --filter @kungal/core
// gen:icons`. The @iconify-json packages stay devDependencies (build-time
// only); the generated literal is what ships.

import { readFileSync, writeFileSync } from 'node:fs'

// Names KunUI's own components use (current + the full set from the original
// lib, so future component ports already have their icons bundled).
const WANT = {
  lucide: [
    'x', 'check', 'info', 'circle-check', 'circle-x', 'triangle-alert',
    'chevron-right', 'chevron-left', 'chevron-down', 'chevrons-right',
    'chevrons-left', 'arrow-right', 'arrow-left', 'zoom-in', 'zoom-out',
    'rotate-cw', 'rotate-ccw', 'refresh-ccw', 'external-link', 'download',
    'copy', 'calendar', 'lollipop',
  ],
  'svg-spinners': ['90-ring-with-bg'],
}

const PKG = {
  lucide: '@iconify-json/lucide',
  'svg-spinners': '@iconify-json/svg-spinners',
}

const out = {}
for (const [prefix, names] of Object.entries(WANT)) {
  const json = JSON.parse(
    readFileSync(
      new URL(`../node_modules/${PKG[prefix]}/icons.json`, import.meta.url),
      'utf8'
    )
  )
  const cw = json.width ?? 16
  const ch = json.height ?? 16
  for (const name of names) {
    const icon = json.icons[name]
    if (!icon) {
      console.error(`MISSING ${prefix}:${name}`)
      process.exit(1)
    }
    const data = { body: icon.body }
    const w = icon.width ?? cw
    const h = icon.height ?? ch
    // viewBox defaults to 0 0 24 24 in the renderer; only store overrides.
    if (w !== 24) data.width = w
    if (h !== 24) data.height = h
    out[`${prefix}:${name}`] = data
  }
}

const entries = Object.entries(out)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join('\n')

const file = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Regenerate: pnpm --filter @kungal/core gen:icons
import type { KunIconData } from './icons'

// SVG data for the icons KunUI components render, bundled inline so the
// library never fetches an icon at runtime. Bodies use currentColor.
export const KUN_BUNDLED_ICONS: Record<string, KunIconData> = {
${entries}
}
`

writeFileSync(new URL('../src/icons-data.ts', import.meta.url), file)
console.log(`gen-icons: wrote ${entries.split('\n').length} icons to src/icons-data.ts`)
