// AUTO-GENERATED by packages/ui-tokens/scripts/gen-tokens.mjs — DO NOT EDIT.
// Regenerate: pnpm --filter @kungal/ui-tokens gen

/// The KunUI blur scale, used by `blur-*` and `backdrop-blur-*`.
///
/// The values are Tailwind v4's default theme, which KunUI's components are
/// written against and never redeclare. A site that overrides them in its own
/// `@theme` renders differently from these; these are what the components
/// were designed at.
///
/// A step is a Gaussian standard deviation in logical pixels. CSS `blur()`
/// and `ImageFilter.blur` both take exactly that, so a step passes straight
/// through: `ImageFilter.blur(sigmaX: KunBlur.sm, sigmaY: KunBlur.sm)`.
/// `BoxShadow.blurRadius` is a different unit; see `KunShadows`.
///
/// A Dart name cannot start with a digit, so `2xl` is `xl2`.
abstract final class KunBlur {
  /// Web `--blur-xs`.
  static const double xs = 4;

  /// Web `--blur-sm`.
  static const double sm = 8;

  /// Web `--blur-md`.
  static const double md = 12;

  /// Web `--blur-lg`.
  static const double lg = 16;

  /// Web `--blur-xl`.
  static const double xl = 24;

  /// Web `--blur-2xl`.
  static const double xl2 = 40;

  /// Web `--blur-3xl`.
  static const double xl3 = 64;
}
