// AUTO-GENERATED by packages/ui-tokens/scripts/gen-tokens.mjs — DO NOT EDIT.
// Regenerate: pnpm --filter @kungal/ui-tokens gen

import 'dart:ui';

/// One semantic hue: an 11-step tint ramp, the solid fill, and the color
/// that stays legible on that fill.
///
/// The dark ramp is the mirror of the light one (50 <-> 950, 500 fixed), so
/// a step key names the same tint weight in both modes.
class KunColorScale {
  /// Creates a scale with every step given explicitly.
  const KunColorScale({
    required this.shade50,
    required this.shade100,
    required this.shade200,
    required this.shade300,
    required this.shade400,
    required this.shade500,
    required this.shade600,
    required this.shade700,
    required this.shade800,
    required this.shade900,
    required this.shade950,
    required this.solid,
    required this.onSolid,
  });

  /// Web token `--color-<hue>-50`, the ramp's faintest step — a tint that
  /// barely lifts off the mode's background.
  final Color shade50;

  /// Web token `--color-<hue>-100`.
  final Color shade100;

  /// Web token `--color-<hue>-200`.
  final Color shade200;

  /// Web token `--color-<hue>-300`.
  final Color shade300;

  /// Web token `--color-<hue>-400`.
  final Color shade400;

  /// Web token `--color-<hue>-500`, the ramp's fixed midpoint — the one step
  /// whose value is identical in light and dark.
  final Color shade500;

  /// Web token `--color-<hue>-600`.
  final Color shade600;

  /// Web token `--color-<hue>-700`.
  final Color shade700;

  /// Web token `--color-<hue>-800`.
  final Color shade800;

  /// Web token `--color-<hue>-900`.
  final Color shade900;

  /// Web token `--color-<hue>-950`, the ramp's strongest step — the most
  /// contrast against the mode's background.
  final Color shade950;

  /// Web token `--color-<hue>`, the brand fill: buttons, badges, chips.
  final Color solid;

  /// Web token `--color-<hue>-foreground`, for text and icons drawn on `solid`.
  ///
  /// Contrast against `solid` is at least 4.5:1 (WCAG AA) in both modes by
  /// construction: the generator measures every pair and fails the build when
  /// one misses.
  final Color onSolid;
}

/// Every KunUI color for one mode.
///
/// The two generated instances are `KunColors.light` and `KunColors.dark`.
class KunColorScheme {
  /// Creates a scheme with every surface and hue given explicitly.
  const KunColorScheme({
    required this.background,
    required this.foreground,
    required this.content1,
    required this.content2,
    required this.content3,
    required this.content4,
    required this.primary,
    required this.secondary,
    required this.success,
    required this.warning,
    required this.danger,
    required this.info,
    required this.neutral,
  });

  /// Web token `--color-background`, the page beneath everything.
  ///
  /// The opaque base color. The web layer composites glass and alpha
  /// surfaces on top of it per component; nothing here is translucent.
  final Color background;

  /// Web token `--color-foreground`, the default text color.
  final Color foreground;

  /// Web token `--color-content1`, the raised surface: cards, popovers,
  /// menus, inputs.
  final Color content1;

  /// Web token `--color-content2`, a shallow well (hover, tracks).
  final Color content2;

  /// Web token `--color-content3`, a deeper well.
  final Color content3;

  /// Web token `--color-content4`, the deepest neutral fill.
  final Color content4;

  /// The brand hue — blue.
  final KunColorScale primary;

  /// The secondary hue — magenta.
  final KunColorScale secondary;

  /// The success hue — green.
  final KunColorScale success;

  /// The warning hue — amber.
  final KunColorScale warning;

  /// The danger hue — red.
  final KunColorScale danger;

  /// The informational hue — cyan.
  final KunColorScale info;

  /// The neutral hue — near-grey.
  ///
  /// Named `neutral` rather than the web token name `default`, which is a
  /// Dart reserved word.
  final KunColorScale neutral;
}

/// The two generated KunUI color schemes.
abstract final class KunColors {
  /// The light scheme — what `:root` ships on the web.
  static const KunColorScheme light = KunColorScheme(
    background: Color.from(alpha: 1, red: 0.9569, green: 0.9569, blue: 0.9687),
    foreground: Color.from(alpha: 1, red: 0.0684, green: 0.0958, blue: 0.1116),
    content1: Color.from(alpha: 1, red: 1, green: 1, blue: 1),
    content2: Color.from(alpha: 1, red: 0.958, green: 0.958, blue: 0.9621),
    content3: Color.from(alpha: 1, red: 0.8941, green: 0.8941, blue: 0.906),
    content4: Color.from(alpha: 1, red: 0.832, green: 0.832, blue: 0.8481),
    primary: KunColorScale(
      shade50: Color.from(alpha: 1, red: 0.9425, green: 0.9658, blue: 1),
      shade100: Color.from(alpha: 1, red: 0.8869, green: 0.9327, blue: 1),
      shade200: Color.from(alpha: 1, red: 0.7773, green: 0.8674, blue: 0.9998),
      shade300: Color.from(alpha: 1, red: 0.6261, green: 0.7774, blue: 0.9999),
      shade400: Color.from(alpha: 1, red: 0.3953, green: 0.6405, blue: 1),
      shade500: Color.from(alpha: 1, red: 0.1572, green: 0.5068, blue: 0.9852),
      shade600: Color.from(alpha: 1, red: 0, green: 0.3852, blue: 0.831),
      shade700: Color.from(alpha: 1, red: 0, green: 0.3023, blue: 0.664),
      shade800: Color.from(alpha: 1, red: 0, green: 0.223, blue: 0.5045),
      shade900: Color.from(alpha: 1, red: 0, green: 0.1481, blue: 0.3536),
      shade950: Color.from(alpha: 1, red: 0.0001, green: 0.091, blue: 0.2386),
      solid: Color.from(alpha: 1, red: 0.0714, green: 0.4437, blue: 0.9166),
      onSolid: Color.from(alpha: 1, red: 1, green: 1, blue: 1),
    ),
    secondary: KunColorScale(
      shade50: Color.from(alpha: 1, red: 1, green: 0.9462, blue: 0.9775),
      shade100: Color.from(alpha: 1, red: 0.9999, green: 0.8935, blue: 0.9564),
      shade200: Color.from(alpha: 1, red: 1, green: 0.7864, blue: 0.9169),
      shade300: Color.from(alpha: 1, red: 1, green: 0.6287, blue: 0.8674),
      shade400: Color.from(alpha: 1, red: 1, green: 0.3268, blue: 0.8047),
      shade500: Color.from(alpha: 1, red: 0.8895, green: 0.0809, blue: 0.6974),
      shade600: Color.from(alpha: 1, red: 0.71, green: 0.0002, blue: 0.5526),
      shade700: Color.from(alpha: 1, red: 0.5659, green: 0, blue: 0.4381),
      shade800: Color.from(alpha: 1, red: 0.4282, green: 0, blue: 0.3288),
      shade900: Color.from(alpha: 1, red: 0.2979, green: 0.0001, blue: 0.2253),
      shade950: Color.from(alpha: 1, red: 0.1987, green: 0, blue: 0.1465),
      solid: Color.from(alpha: 1, red: 1, green: 0.5808, blue: 0.8545),
      onSolid: Color.from(alpha: 1, red: 0.1229, green: 0.0645, blue: 0.1017),
    ),
    success: KunColorScale(
      shade50: Color.from(alpha: 1, red: 0.8829, green: 1, blue: 0.905),
      shade100: Color.from(alpha: 1, red: 0.7543, green: 1, blue: 0.8069),
      shade200: Color.from(alpha: 1, red: 0.4498, green: 0.9896, blue: 0.6106),
      shade300: Color.from(alpha: 1, red: 0.3449, green: 0.8941, blue: 0.5214),
      shade400: Color.from(alpha: 1, red: 0.1637, green: 0.7578, blue: 0.394),
      shade500: Color.from(alpha: 1, red: 0, green: 0.631, blue: 0.3026),
      shade600: Color.from(alpha: 1, red: 0.0003, green: 0.4956, blue: 0.2321),
      shade700: Color.from(alpha: 1, red: 0.0004, green: 0.3918, blue: 0.178),
      shade800: Color.from(alpha: 1, red: 0, green: 0.2927, blue: 0.1262),
      shade900: Color.from(alpha: 1, red: 0, green: 0.199, blue: 0.0774),
      shade950: Color.from(alpha: 1, red: 0, green: 0.1276, blue: 0.0401),
      solid: Color.from(alpha: 1, red: 0.1744, green: 0.7642, blue: 0.4),
      onSolid: Color.from(alpha: 1, red: 0.0441, green: 0.1015, blue: 0.0584),
    ),
    warning: KunColorScale(
      shade50: Color.from(alpha: 1, red: 1, green: 0.9565, blue: 0.905),
      shade100: Color.from(alpha: 1, red: 1, green: 0.9138, blue: 0.8108),
      shade200: Color.from(alpha: 1, red: 1, green: 0.8271, blue: 0.6141),
      shade300: Color.from(alpha: 1, red: 1, green: 0.7005, blue: 0.2712),
      shade400: Color.from(alpha: 1, red: 0.8647, green: 0.5672, blue: 0.0008),
      shade500: Color.from(alpha: 1, red: 0.7146, green: 0.4656, blue: 0.0002),
      shade600: Color.from(alpha: 1, red: 0.5627, green: 0.3629, blue: 0.0003),
      shade700: Color.from(alpha: 1, red: 0.4463, green: 0.2841, blue: 0.0001),
      shade800: Color.from(alpha: 1, red: 0.3351, green: 0.2089, blue: 0),
      shade900: Color.from(alpha: 1, red: 0.23, green: 0.1377, blue: 0),
      shade950: Color.from(alpha: 1, red: 0.1498, green: 0.0835, blue: 0),
      solid: Color.from(alpha: 1, red: 0.9999, green: 0.6627, blue: 0.0637),
      onSolid: Color.from(alpha: 1, red: 0.1192, green: 0.0772, blue: 0.0241),
    ),
    danger: KunColorScale(
      shade50: Color.from(alpha: 1, red: 1, green: 0.9497, blue: 0.9542),
      shade100: Color.from(alpha: 1, red: 1, green: 0.9005, blue: 0.9099),
      shade200: Color.from(alpha: 1, red: 1, green: 0.8016, blue: 0.8228),
      shade300: Color.from(alpha: 1, red: 1, green: 0.6594, blue: 0.7036),
      shade400: Color.from(alpha: 1, red: 1, green: 0.4121, blue: 0.5263),
      shade500: Color.from(alpha: 1, red: 0.9364, green: 0.148, blue: 0.3876),
      shade600: Color.from(alpha: 1, red: 0.7614, green: 0.0006, blue: 0.2912),
      shade700: Color.from(alpha: 1, red: 0.6076, green: 0, blue: 0.2259),
      shade800: Color.from(alpha: 1, red: 0.4606, green: 0, blue: 0.1636),
      shade900: Color.from(alpha: 1, red: 0.3216, green: 0.0001, blue: 0.1047),
      shade950: Color.from(alpha: 1, red: 0.2157, green: 0.0001, blue: 0.0598),
      solid: Color.from(alpha: 1, red: 0.8783, green: 0.0225, blue: 0.3429),
      onSolid: Color.from(alpha: 1, red: 1, green: 1, blue: 1),
    ),
    info: KunColorScale(
      shade50: Color.from(alpha: 1, red: 0.9086, green: 0.9782, blue: 1),
      shade100: Color.from(alpha: 1, red: 0.8171, green: 0.9566, blue: 1),
      shade200: Color.from(alpha: 1, red: 0.6201, green: 0.9127, blue: 0.9999),
      shade300: Color.from(alpha: 1, red: 0.2202, green: 0.849, blue: 1),
      shade400: Color.from(alpha: 1, red: 0, green: 0.7112, blue: 0.8502),
      shade500: Color.from(alpha: 1, red: 0.0014, green: 0.5861, blue: 0.7023),
      shade600: Color.from(alpha: 1, red: 0.0006, green: 0.4596, blue: 0.5529),
      shade700: Color.from(alpha: 1, red: 0.0001, green: 0.3626, blue: 0.4383),
      shade800: Color.from(alpha: 1, red: 0, green: 0.27, blue: 0.3289),
      shade900: Color.from(alpha: 1, red: 0, green: 0.1824, blue: 0.2254),
      shade950: Color.from(alpha: 1, red: 0.0002, green: 0.1156, blue: 0.1465),
      solid: Color.from(alpha: 1, red: 0, green: 0.6911, blue: 0.8265),
      onSolid: Color.from(alpha: 1, red: 0.0161, green: 0.0989, blue: 0.1221),
    ),
    neutral: KunColorScale(
      shade50: Color.from(alpha: 1, red: 0.9592, green: 0.9594, blue: 0.9998),
      shade100: Color.from(alpha: 1, red: 0.9236, green: 0.9238, blue: 0.9677),
      shade200: Color.from(alpha: 1, red: 0.8552, green: 0.8554, blue: 0.8987),
      shade300: Color.from(alpha: 1, red: 0.764, green: 0.7642, blue: 0.8066),
      shade400: Color.from(alpha: 1, red: 0.6346, green: 0.6347, blue: 0.6756),
      shade500: Color.from(alpha: 1, red: 0.5215, green: 0.5216, blue: 0.5611),
      shade600: Color.from(alpha: 1, red: 0.4072, green: 0.4071, blue: 0.4449),
      shade700: Color.from(alpha: 1, red: 0.3196, green: 0.3194, blue: 0.3556),
      shade800: Color.from(alpha: 1, red: 0.2359, green: 0.2357, blue: 0.2701),
      shade900: Color.from(alpha: 1, red: 0.1568, green: 0.1565, blue: 0.1887),
      shade950: Color.from(alpha: 1, red: 0.0967, green: 0.0961, blue: 0.1263),
      solid: Color.from(alpha: 1, red: 0.4409, green: 0.4409, blue: 0.4792),
      onSolid: Color.from(alpha: 1, red: 1, green: 1, blue: 1),
    ),
  );

  /// The dark scheme — what `.kun-dark-mode` ships on the web.
  static const KunColorScheme dark = KunColorScheme(
    background: Color.from(alpha: 1, red: 0.0392, green: 0.0392, blue: 0.0392),
    foreground: Color.from(alpha: 1, red: 0.9258, green: 0.9299, blue: 0.934),
    content1: Color.from(alpha: 1, red: 0.094, green: 0.094, blue: 0.106),
    content2: Color.from(alpha: 1, red: 0.1536, green: 0.1536, blue: 0.1664),
    content3: Color.from(alpha: 1, red: 0.247, green: 0.247, blue: 0.2731),
    content4: Color.from(alpha: 1, red: 0.323, green: 0.323, blue: 0.3571),
    primary: KunColorScale(
      shade50: Color.from(alpha: 1, red: 0.0001, green: 0.091, blue: 0.2386),
      shade100: Color.from(alpha: 1, red: 0, green: 0.1481, blue: 0.3536),
      shade200: Color.from(alpha: 1, red: 0, green: 0.223, blue: 0.5045),
      shade300: Color.from(alpha: 1, red: 0, green: 0.3023, blue: 0.664),
      shade400: Color.from(alpha: 1, red: 0, green: 0.3852, blue: 0.831),
      shade500: Color.from(alpha: 1, red: 0.1572, green: 0.5068, blue: 0.9852),
      shade600: Color.from(alpha: 1, red: 0.3953, green: 0.6405, blue: 1),
      shade700: Color.from(alpha: 1, red: 0.6261, green: 0.7774, blue: 0.9999),
      shade800: Color.from(alpha: 1, red: 0.7773, green: 0.8674, blue: 0.9998),
      shade900: Color.from(alpha: 1, red: 0.8869, green: 0.9327, blue: 1),
      shade950: Color.from(alpha: 1, red: 0.9425, green: 0.9658, blue: 1),
      solid: Color.from(alpha: 1, red: 0.0714, green: 0.4437, blue: 0.9166),
      onSolid: Color.from(alpha: 1, red: 1, green: 1, blue: 1),
    ),
    secondary: KunColorScale(
      shade50: Color.from(alpha: 1, red: 0.1987, green: 0, blue: 0.1465),
      shade100: Color.from(alpha: 1, red: 0.2979, green: 0.0001, blue: 0.2253),
      shade200: Color.from(alpha: 1, red: 0.4282, green: 0, blue: 0.3288),
      shade300: Color.from(alpha: 1, red: 0.5659, green: 0, blue: 0.4381),
      shade400: Color.from(alpha: 1, red: 0.71, green: 0.0002, blue: 0.5526),
      shade500: Color.from(alpha: 1, red: 0.8895, green: 0.0809, blue: 0.6974),
      shade600: Color.from(alpha: 1, red: 1, green: 0.3268, blue: 0.8047),
      shade700: Color.from(alpha: 1, red: 1, green: 0.6287, blue: 0.8674),
      shade800: Color.from(alpha: 1, red: 1, green: 0.7864, blue: 0.9169),
      shade900: Color.from(alpha: 1, red: 0.9999, green: 0.8935, blue: 0.9564),
      shade950: Color.from(alpha: 1, red: 1, green: 0.9462, blue: 0.9775),
      solid: Color.from(alpha: 1, red: 1, green: 0.5808, blue: 0.8545),
      onSolid: Color.from(alpha: 1, red: 0.1229, green: 0.0645, blue: 0.1017),
    ),
    success: KunColorScale(
      shade50: Color.from(alpha: 1, red: 0, green: 0.1276, blue: 0.0401),
      shade100: Color.from(alpha: 1, red: 0, green: 0.199, blue: 0.0774),
      shade200: Color.from(alpha: 1, red: 0, green: 0.2927, blue: 0.1262),
      shade300: Color.from(alpha: 1, red: 0.0004, green: 0.3918, blue: 0.178),
      shade400: Color.from(alpha: 1, red: 0.0003, green: 0.4956, blue: 0.2321),
      shade500: Color.from(alpha: 1, red: 0, green: 0.631, blue: 0.3026),
      shade600: Color.from(alpha: 1, red: 0.1637, green: 0.7578, blue: 0.394),
      shade700: Color.from(alpha: 1, red: 0.3449, green: 0.8941, blue: 0.5214),
      shade800: Color.from(alpha: 1, red: 0.4498, green: 0.9896, blue: 0.6106),
      shade900: Color.from(alpha: 1, red: 0.7543, green: 1, blue: 0.8069),
      shade950: Color.from(alpha: 1, red: 0.8829, green: 1, blue: 0.905),
      solid: Color.from(alpha: 1, red: 0.1744, green: 0.7642, blue: 0.4),
      onSolid: Color.from(alpha: 1, red: 0.0441, green: 0.1015, blue: 0.0584),
    ),
    warning: KunColorScale(
      shade50: Color.from(alpha: 1, red: 0.1498, green: 0.0835, blue: 0),
      shade100: Color.from(alpha: 1, red: 0.23, green: 0.1377, blue: 0),
      shade200: Color.from(alpha: 1, red: 0.3351, green: 0.2089, blue: 0),
      shade300: Color.from(alpha: 1, red: 0.4463, green: 0.2841, blue: 0.0001),
      shade400: Color.from(alpha: 1, red: 0.5627, green: 0.3629, blue: 0.0003),
      shade500: Color.from(alpha: 1, red: 0.7146, green: 0.4656, blue: 0.0002),
      shade600: Color.from(alpha: 1, red: 0.8647, green: 0.5672, blue: 0.0008),
      shade700: Color.from(alpha: 1, red: 1, green: 0.7005, blue: 0.2712),
      shade800: Color.from(alpha: 1, red: 1, green: 0.8271, blue: 0.6141),
      shade900: Color.from(alpha: 1, red: 1, green: 0.9138, blue: 0.8108),
      shade950: Color.from(alpha: 1, red: 1, green: 0.9565, blue: 0.905),
      solid: Color.from(alpha: 1, red: 0.9999, green: 0.6627, blue: 0.0637),
      onSolid: Color.from(alpha: 1, red: 0.1192, green: 0.0772, blue: 0.0241),
    ),
    danger: KunColorScale(
      shade50: Color.from(alpha: 1, red: 0.2157, green: 0.0001, blue: 0.0598),
      shade100: Color.from(alpha: 1, red: 0.3216, green: 0.0001, blue: 0.1047),
      shade200: Color.from(alpha: 1, red: 0.4606, green: 0, blue: 0.1636),
      shade300: Color.from(alpha: 1, red: 0.6076, green: 0, blue: 0.2259),
      shade400: Color.from(alpha: 1, red: 0.7614, green: 0.0006, blue: 0.2912),
      shade500: Color.from(alpha: 1, red: 0.9364, green: 0.148, blue: 0.3876),
      shade600: Color.from(alpha: 1, red: 1, green: 0.4121, blue: 0.5263),
      shade700: Color.from(alpha: 1, red: 1, green: 0.6594, blue: 0.7036),
      shade800: Color.from(alpha: 1, red: 1, green: 0.8016, blue: 0.8228),
      shade900: Color.from(alpha: 1, red: 1, green: 0.9005, blue: 0.9099),
      shade950: Color.from(alpha: 1, red: 1, green: 0.9497, blue: 0.9542),
      solid: Color.from(alpha: 1, red: 0.8783, green: 0.0225, blue: 0.3429),
      onSolid: Color.from(alpha: 1, red: 1, green: 1, blue: 1),
    ),
    info: KunColorScale(
      shade50: Color.from(alpha: 1, red: 0.0002, green: 0.1156, blue: 0.1465),
      shade100: Color.from(alpha: 1, red: 0, green: 0.1824, blue: 0.2254),
      shade200: Color.from(alpha: 1, red: 0, green: 0.27, blue: 0.3289),
      shade300: Color.from(alpha: 1, red: 0.0001, green: 0.3626, blue: 0.4383),
      shade400: Color.from(alpha: 1, red: 0.0006, green: 0.4596, blue: 0.5529),
      shade500: Color.from(alpha: 1, red: 0.0014, green: 0.5861, blue: 0.7023),
      shade600: Color.from(alpha: 1, red: 0, green: 0.7112, blue: 0.8502),
      shade700: Color.from(alpha: 1, red: 0.2202, green: 0.849, blue: 1),
      shade800: Color.from(alpha: 1, red: 0.6201, green: 0.9127, blue: 0.9999),
      shade900: Color.from(alpha: 1, red: 0.8171, green: 0.9566, blue: 1),
      shade950: Color.from(alpha: 1, red: 0.9086, green: 0.9782, blue: 1),
      solid: Color.from(alpha: 1, red: 0, green: 0.6911, blue: 0.8265),
      onSolid: Color.from(alpha: 1, red: 0.0161, green: 0.0989, blue: 0.1221),
    ),
    neutral: KunColorScale(
      shade50: Color.from(alpha: 1, red: 0.0967, green: 0.0961, blue: 0.1263),
      shade100: Color.from(alpha: 1, red: 0.1568, green: 0.1565, blue: 0.1887),
      shade200: Color.from(alpha: 1, red: 0.2359, green: 0.2357, blue: 0.2701),
      shade300: Color.from(alpha: 1, red: 0.3196, green: 0.3194, blue: 0.3556),
      shade400: Color.from(alpha: 1, red: 0.4072, green: 0.4071, blue: 0.4449),
      shade500: Color.from(alpha: 1, red: 0.5215, green: 0.5216, blue: 0.5611),
      shade600: Color.from(alpha: 1, red: 0.6346, green: 0.6347, blue: 0.6756),
      shade700: Color.from(alpha: 1, red: 0.764, green: 0.7642, blue: 0.8066),
      shade800: Color.from(alpha: 1, red: 0.8552, green: 0.8554, blue: 0.8987),
      shade900: Color.from(alpha: 1, red: 0.9236, green: 0.9238, blue: 0.9677),
      shade950: Color.from(alpha: 1, red: 0.9592, green: 0.9594, blue: 0.9998),
      solid: Color.from(alpha: 1, red: 0.4409, green: 0.4409, blue: 0.4792),
      onSolid: Color.from(alpha: 1, red: 1, green: 1, blue: 1),
    ),
  );
}
