// AUTO-GENERATED by packages/ui-tokens/scripts/gen-tokens.mjs — DO NOT EDIT.
// Regenerate: pnpm --filter @kungal/ui-tokens gen

/// The KunUI container widths, in logical pixels: what a named size in
/// `max-w-*`, `w-*` and the other sizing utilities resolves to.
///
/// The values are Tailwind v4's default theme, which KunUI's components are
/// written against and never redeclare. A site that overrides them in its own
/// `@theme` renders differently from these; these are what the components
/// were designed at.
///
/// A Dart name cannot start with a digit, so `3xs` is `xs3` and `2xl` is
/// `xl2`.
abstract final class KunContainerWidths {
  /// Web `--container-3xs`.
  static const double xs3 = 256;

  /// Web `--container-2xs`.
  static const double xs2 = 288;

  /// Web `--container-xs`.
  static const double xs = 320;

  /// Web `--container-sm`.
  static const double sm = 384;

  /// Web `--container-md`.
  static const double md = 448;

  /// Web `--container-lg`.
  static const double lg = 512;

  /// Web `--container-xl`.
  static const double xl = 576;

  /// Web `--container-2xl`.
  static const double xl2 = 672;

  /// Web `--container-3xl`.
  static const double xl3 = 768;

  /// Web `--container-4xl`.
  static const double xl4 = 896;

  /// Web `--container-5xl`.
  static const double xl5 = 1024;

  /// Web `--container-6xl`.
  static const double xl6 = 1152;

  /// Web `--container-7xl`.
  static const double xl7 = 1280;
}

/// The KunUI responsive breakpoints, in logical pixels. A web `md:` class
/// applies from `width >= md`, and a `max-md:` class below it.
///
/// The values are Tailwind v4's default theme, which KunUI's components are
/// written against and never redeclare. A site that overrides them in its own
/// `@theme` renders differently from these; these are what the components
/// were designed at.
///
/// A Dart name cannot start with a digit, so `2xl` is `xl2`.
abstract final class KunBreakpointWidths {
  /// Web `--breakpoint-sm`.
  static const double sm = 640;

  /// Web `--breakpoint-md`.
  static const double md = 768;

  /// Web `--breakpoint-lg`.
  static const double lg = 1024;

  /// Web `--breakpoint-xl`.
  static const double xl = 1280;

  /// Web `--breakpoint-2xl`.
  static const double xl2 = 1536;
}
