// AUTO-GENERATED by packages/ui-tokens/scripts/gen-tokens.mjs — DO NOT EDIT.
// Regenerate: pnpm --filter @kungal/ui-tokens gen

import 'package:flutter/animation.dart';

/// The KunUI easing set — one rhythm every component shares.
///
/// Asymmetric by design: decelerate on enter, accelerate on exit.
abstract final class KunEasing {
  /// Web token `--ease-kun-standard`, the default in-screen transition.
  static const Curve standard = Cubic(0.2, 0, 0, 1);

  /// Web token `--ease-kun-out` — decelerate, for entering elements.
  static const Curve enter = Cubic(0, 0, 0, 1);

  /// Web token `--ease-kun-in` — accelerate, for leaving elements.
  ///
  /// Named `exit` because `in` is a Dart reserved word.
  static const Curve exit = Cubic(0.3, 0, 1, 1);

  /// Web token `--ease-kun-emphasized`, the premium settle.
  static const Curve emphasized = Cubic(0.16, 1, 0.3, 1);
}

/// The KunUI duration scale.
///
/// `Duration` is `dart:core`; the import above is for `Curve` and `Cubic`.
abstract final class KunDurations {
  /// Web token `--kun-dur-fast`, for hover, selection and micro-interactions.
  static const Duration fast = Duration(milliseconds: 150);

  /// Web token `--kun-dur-base`, for component enter and in-screen moves.
  static const Duration base = Duration(milliseconds: 250);

  /// Web token `--kun-dur-slow`, for larger surfaces.
  static const Duration slow = Duration(milliseconds: 350);

  /// Web token `--kun-dur-exit`. Exits run about 30% shorter than enters.
  static const Duration exit = Duration(milliseconds: 180);
}
