// AUTO-GENERATED by packages/ui-tokens/scripts/gen-tokens.mjs — DO NOT EDIT.
// Regenerate: pnpm --filter @kungal/ui-tokens gen

import 'package:flutter/animation.dart';

/// The KunUI easing set — one rhythm every component shares.
///
/// Asymmetric by design: decelerate on enter, accelerate on exit.
abstract final class KunEasing {
  /// Web token `--ease-kun-standard`, the default in-screen transition.
  static const Curve standard = Cubic(0.2, 0, 0, 1);

  /// Web token `--ease-kun-out` — decelerate, for entering elements.
  static const Curve enter = Cubic(0, 0, 0, 1);

  /// Web token `--ease-kun-in` — accelerate, for leaving elements.
  ///
  /// Named `exit` because `in` is a Dart reserved word.
  static const Curve exit = Cubic(0.3, 0, 1, 1);

  /// Web token `--ease-kun-emphasized`, the premium settle.
  static const Curve emphasized = Cubic(0.16, 1, 0.3, 1);
}

/// The KunUI duration scale.
///
/// `Duration` is `dart:core`; the import above is for `Curve` and `Cubic`.
abstract final class KunDurations {
  /// Web token `--kun-dur-fast`, for hover, selection and micro-interactions.
  static const Duration fast = Duration(milliseconds: 150);

  /// Web token `--kun-dur-base`, for component enter and in-screen moves.
  static const Duration base = Duration(milliseconds: 250);

  /// Web token `--kun-dur-slow`, for larger surfaces.
  static const Duration slow = Duration(milliseconds: 350);

  /// Web token `--kun-dur-exit`. Exits run about 30% shorter than enters.
  static const Duration exit = Duration(milliseconds: 180);
}

/// What a web transition utility (`transition`, `transition-colors`, …)
/// runs at when the component names no `duration-*` or `ease-*`: most of
/// KunUI's hover and press feedback.
///
/// The values are Tailwind v4's default theme, which KunUI's components are
/// written against and never redeclare. A site that overrides them in its own
/// `@theme` renders differently from these; these are what the components
/// were designed at.
abstract final class KunDefaultTransition {
  /// Web `--default-transition-duration`.
  static const Duration duration = Duration(milliseconds: 150);

  /// Web `--default-transition-timing-function`.
  static const Curve curve = Cubic(0.4, 0, 0.2, 1);
}

/// Web `animate-pulse`: a loading placeholder fading down and back up,
/// over and over.
///
/// The values are Tailwind v4's default theme, which KunUI's components are
/// written against and never redeclare. A site that overrides them in its own
/// `@theme` renders differently from these; these are what the components
/// were designed at.
///
/// The web eases each half of a cycle with [curve], down to [midOpacity]
/// and back, rather than easing the whole cycle once. [curve] is symmetric,
/// so an `AnimationController` of half [duration] running
/// `repeat(reverse: true)` under a `CurvedAnimation` with [curve] draws the
/// same fade.
abstract final class KunPulse {
  /// One full cycle: web `--animate-pulse`.
  static const Duration duration = Duration(milliseconds: 2000);

  /// The ease of each half-cycle.
  static const Curve curve = Cubic(0.4, 0, 0.6, 1);

  /// The opacity half-way through a cycle, which starts and ends at the
  /// widget's own opacity.
  static const double midOpacity = 0.5;
}

/// Web `animate-spin`: one clockwise turn per [duration] at constant speed,
/// over and over.
///
/// The values are Tailwind v4's default theme, which KunUI's components are
/// written against and never redeclare. A site that overrides them in its own
/// `@theme` renders differently from these; these are what the components
/// were designed at.
abstract final class KunSpin {
  /// One full turn: web `--animate-spin`.
  static const Duration duration = Duration(milliseconds: 1000);

  /// Constant speed: web `linear`.
  static const Curve curve = Curves.linear;
}

/// The ballistic model behind the web `KunShatter` component, as data.
///
/// These are the physics parameters one level above the sampled keyframes:
/// the web bakes its per-shard WAAPI keyframes from exactly these numbers,
/// so a Flutter shatter that samples this model reproduces the same motion
/// instead of re-tuning the feel by eye.
///
/// The model, per shard (rng() uniform in [0,1); lengths in logical px):
/// ```
/// reach   = spread × elementDiagonal × reachFactor
/// launch  = reach × (launchMin + rng·launchSpan)
/// vx, vy  = dirX × launch,  dirY × launch × verticalFactor
/// g       = gravity × reach × (gravityMin + rng·gravitySpan)
/// ```
/// over normalised time t ∈ [0,1], sampled into [keyframeSteps] linear
/// segments:
/// ```
/// drag(t)  = 1 − (1−t)^dragExponent
/// x(t)     = vx·drag(t)
/// y(t)     = vy·drag(t) + g·t²
/// rot(t)   = spin·t,  spin = (2·rng−1) × rotation
/// scale(t) = 1 − (1−scaleEnd)·t
/// ```
/// Gravity is a t² acceleration, not a linear end-offset, and the samples
/// are joined linearly — one fat ease over the whole flight reads as
/// "snap, then freeze" rather than physical.
abstract final class KunShatterPhysics {
  /// How many linear keyframe segments each trajectory is sampled into.
  static const int keyframeSteps = 16;

  /// reach = spread × elementDiagonal × `reachFactor` — the distance scale
  /// every other length-like constant multiplies.
  static const double reachFactor = 0.5;

  /// Outward launch speed, in units of reach:
  /// `launchMin` + rng·`launchSpan`. A gentle push, not a hard snap.
  static const double launchMin = 0.32;

  /// The random span above [launchMin].
  static const double launchSpan = 0.55;

  /// Vertical launch damping — shards fly a little flatter than their
  /// radial direction, and gravity then owns the vertical.
  static const double verticalFactor = 0.8;

  /// Downward acceleration, in units of reach, applied ×t²:
  /// `gravityMin` + rng·`gravitySpan`.
  static const double gravityMin = 0.85;

  /// The random span above [gravityMin].
  static const double gravitySpan = 0.5;

  /// drag(t) = 1 − (1−t)^`dragExponent` — how fast the launch impulse
  /// decays against air drag.
  static const double dragExponent = 1.7;

  /// Shards shrink slightly as they fly: end scale =
  /// `scaleEndMin` + rng·`scaleEndSpan`.
  static const double scaleEndMin = 0.8;

  /// The random span above [scaleEndMin].
  static const double scaleEndSpan = 0.16;

  /// Fade starts late in the flight, at `fadeOutStartMin` +
  /// rng·`fadeOutStartSpan` of t — the glass is seen flying, not
  /// dissolving.
  static const double fadeOutStartMin = 0.5;

  /// The random span above [fadeOutStartMin].
  static const double fadeOutStartSpan = 0.18;

  /// Reassemble eases home along 1 − (1−t)^`settleExponent` — decelerate
  /// into place.
  static const double settleExponent = 2;

  /// Reassembling shards fade in over the first `fadeInWindow` of t.
  static const double fadeInWindow = 0.4;

  /// Shards nearest the impact let go first: delay = (dist/maxDist) ×
  /// min(duration×`staggerFraction`, `staggerCapMs`).
  static const double staggerFraction = 0.22;

  /// The stagger ceiling, in milliseconds.
  static const int staggerCapMs = 120;

  /// The tuned flight duration.
  static const Duration defaultDuration = Duration(milliseconds: 1100);

  /// The tuned maximum random spin per shard, in degrees:
  /// spin = (2·rng−1) × rotation.
  static const double defaultRotationDeg = 140;
}

/// Drag-to-dismiss on a bottom sheet — the feel of the web `KunModal` and
/// `KunDrawer` sheets, as data.
///
/// On release the sheet dismisses when it moved down and either
/// ```
/// velocity > closeVelocity
/// offset  >= min(panelHeight, viewportHeight) × closeDistanceRatio
/// ```
/// An upward drag of d px moves the panel
/// `rubberBandLimit × (1 − e^(−d / rubberBandLimit))`: it yields at first
/// and then firmly stops.
///
/// The drag slop, velocity sampling and scroll hand-off are not here: the web
/// tunes those to browser behaviour, and Flutter's gesture arena,
/// `VelocityTracker` and scroll notifications own them.
abstract final class KunSwipeDismissPhysics {
  /// The fraction of the panel height, capped at the viewport, that
  /// dismisses on release.
  static const double closeDistanceRatio = 0.25;

  /// The release velocity that dismisses regardless of distance, in logical
  /// pixels per second — the unit of `DragEndDetails.primaryVelocity`. The
  /// web states it as 0.4 px/ms.
  static const double closeVelocity = 400;

  /// The asymptote of an upward overdrag, in logical pixels.
  static const double rubberBandLimit = 32;
}
