// AUTO-GENERATED by packages/ui-tokens/scripts/gen-tokens.mjs — DO NOT EDIT.
// Regenerate: pnpm --filter @kungal/ui-tokens gen

/// The KunUI corner radius buckets, in logical pixels.
///
/// The web multiplies `sm`, `md` and `lg` by `--kun-radius-scale`, a runtime
/// knob that squares or rounds every corner at once. That knob is a theme
/// concern for a higher layer; `none` and `full` are never scaled.
abstract final class KunRadius {
  /// Web token `--radius-kun-none`. A square corner.
  static const double none = 0;

  /// Web token `--radius-kun-sm`, for small controls.
  static const double sm = 6;

  /// Web token `--radius-kun-md`, the default control radius.
  static const double md = 12;

  /// Web token `--radius-kun-lg`, for containers and floating panels.
  static const double lg = 16;

  /// Web token `--radius-kun-full`. A pill: clamp it to half the height.
  static const double full = 9999;
}
