// AUTO-GENERATED by packages/ui-tokens/scripts/gen-tokens.mjs — DO NOT EDIT.
// Regenerate: pnpm --filter @kungal/ui-tokens gen

import 'package:flutter/painting.dart';

/// The KunUI elevation scale — one shadow per tier, so every floating
/// surface of a kind shares an elevation instead of picking one ad hoc.
abstract final class KunShadows {
  /// Web token `--shadow-kun-sm`, for tooltips and small hints.
  static const List<BoxShadow> sm = [
    BoxShadow(
      color: Color.from(alpha: 0.08, red: 0, green: 0, blue: 0),
      offset: Offset(0, 1),
      blurRadius: 5,
      spreadRadius: -2,
    ),
  ];

  /// Web token `--shadow-kun-md`, for popovers, dropdowns, menus and toasts.
  static const List<BoxShadow> md = [
    BoxShadow(
      color: Color.from(alpha: 0.07, red: 0, green: 0, blue: 0),
      offset: Offset(0, 3),
      blurRadius: 10,
      spreadRadius: -4,
    ),
    BoxShadow(
      color: Color.from(alpha: 0.1, red: 0, green: 0, blue: 0),
      offset: Offset(0, 6),
      blurRadius: 18,
      spreadRadius: -6,
    ),
  ];

  /// Web token `--shadow-kun-lg`, for modals and drawers.
  static const List<BoxShadow> lg = [
    BoxShadow(
      color: Color.from(alpha: 0.11, red: 0, green: 0, blue: 0),
      offset: Offset(0, 6),
      blurRadius: 18,
      spreadRadius: -8,
    ),
    BoxShadow(
      color: Color.from(alpha: 0.16, red: 0, green: 0, blue: 0),
      offset: Offset(0, 12),
      blurRadius: 36,
      spreadRadius: -12,
    ),
  ];
}
