// AUTO-GENERATED by packages/ui-tokens/scripts/gen-tokens.mjs — DO NOT EDIT.
// Regenerate: pnpm --filter @kungal/ui-tokens gen

/// The KunUI spacing scale, in logical pixels.
///
/// The values are Tailwind v4's default theme, which KunUI's components are
/// written against and never redeclare. A site that overrides them in its own
/// `@theme` renders differently from these; these are what the components
/// were designed at.
abstract final class KunSpacing {
  /// Web token `--spacing`, the step every spacing utility multiplies:
  /// `mt-1` is `unit`, `px-4` is `unit * 4`, `py-1.5` is `unit * 1.5`.
  ///
  /// A product of consts is itself const, so `unit * 4` works inside a
  /// `const` widget.
  static const double unit = 4;
}
