// AUTO-GENERATED by packages/ui-tokens/scripts/gen-tokens.mjs — DO NOT EDIT.
// Regenerate: pnpm --filter @kungal/ui-tokens gen

import 'package:flutter/painting.dart';

/// The KunUI type scale: font size and line height, nothing else.
///
/// The values are Tailwind v4's default theme, which KunUI's components are
/// written against and never redeclare. A site that overrides them in its own
/// `@theme` renders differently from these; these are what the components
/// were designed at.
///
/// Color, weight and family are left null, so they inherit from the
/// ambient `DefaultTextStyle`; add them with `copyWith`, taking the weight
/// from [KunFontWeights] and a family from [KunFontFamilies].
///
/// Every style sets `leadingDistribution` to
/// `TextLeadingDistribution.even`, which is CSS's half-leading. Flutter's
/// default, `proportional`, splits the extra line height by the font's
/// ascent/descent ratio, which sets the glyphs lower in the line box than
/// the web does.
///
/// `text-2xl` to `text-9xl` are named `xl2` to `xl9`: a Dart name cannot
/// start with a digit.
abstract final class KunText {
  /// Web `text-xs`: 12px on a 16px line.
  static const TextStyle xs = TextStyle(
    fontSize: 12,
    height: 16 / 12,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-sm`: 14px on a 20px line.
  static const TextStyle sm = TextStyle(
    fontSize: 14,
    height: 20 / 14,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-base`: 16px on a 24px line.
  static const TextStyle base = TextStyle(
    fontSize: 16,
    height: 24 / 16,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-lg`: 18px on a 28px line.
  static const TextStyle lg = TextStyle(
    fontSize: 18,
    height: 28 / 18,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-xl`: 20px on a 28px line.
  static const TextStyle xl = TextStyle(
    fontSize: 20,
    height: 28 / 20,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-2xl`: 24px on a 32px line.
  static const TextStyle xl2 = TextStyle(
    fontSize: 24,
    height: 32 / 24,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-3xl`: 30px on a 36px line.
  static const TextStyle xl3 = TextStyle(
    fontSize: 30,
    height: 36 / 30,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-4xl`: 36px on a 40px line.
  static const TextStyle xl4 = TextStyle(
    fontSize: 36,
    height: 40 / 36,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-5xl`: 48px on a 48px line.
  static const TextStyle xl5 = TextStyle(
    fontSize: 48,
    height: 1,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-6xl`: 60px on a 60px line.
  static const TextStyle xl6 = TextStyle(
    fontSize: 60,
    height: 1,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-7xl`: 72px on a 72px line.
  static const TextStyle xl7 = TextStyle(
    fontSize: 72,
    height: 1,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-8xl`: 96px on a 96px line.
  static const TextStyle xl8 = TextStyle(
    fontSize: 96,
    height: 1,
    leadingDistribution: TextLeadingDistribution.even,
  );

  /// Web `text-9xl`: 128px on a 128px line.
  static const TextStyle xl9 = TextStyle(
    fontSize: 128,
    height: 1,
    leadingDistribution: TextLeadingDistribution.even,
  );
}

/// Tailwind's font weight scale: web `font-medium` is [medium].
///
/// The values are Tailwind v4's default theme, which KunUI's components are
/// written against and never redeclare. A site that overrides them in its own
/// `@theme` renders differently from these; these are what the components
/// were designed at.
abstract final class KunFontWeights {
  /// Web `--font-weight-thin`.
  static const FontWeight thin = FontWeight.w100;

  /// Web `--font-weight-extralight`.
  static const FontWeight extralight = FontWeight.w200;

  /// Web `--font-weight-light`.
  static const FontWeight light = FontWeight.w300;

  /// Web `--font-weight-normal`.
  static const FontWeight normal = FontWeight.w400;

  /// Web `--font-weight-medium`.
  static const FontWeight medium = FontWeight.w500;

  /// Web `--font-weight-semibold`.
  static const FontWeight semibold = FontWeight.w600;

  /// Web `--font-weight-bold`.
  static const FontWeight bold = FontWeight.w700;

  /// Web `--font-weight-extrabold`.
  static const FontWeight extrabold = FontWeight.w800;

  /// Web `--font-weight-black`.
  static const FontWeight black = FontWeight.w900;
}

/// KunUI's font stacks, as Flutter family lists.
///
/// A CSS `font-family` is a list the browser walks until a family is
/// installed; a `TextStyle` takes the first name as `fontFamily` and the
/// rest as `fontFamilyFallback`, which the engine walks the same way.
///
/// These name system fonts. Flutter on the web reaches none of them, so a
/// web build that must show code in a fixed-width face bundles one and
/// puts it first.
abstract final class KunFontFamilies {
  /// Web `--kun-font-mono`, the face `.kun-prose` sets code and `kbd` in:
  /// the first family of `ui-monospace, SFMono-Regular, Menlo, Consolas, Liberation Mono, monospace`
  /// that names an installed font rather than a CSS keyword.
  static const String mono = 'SFMono-Regular';

  /// The rest of the [mono] stack, in order. `monospace` last is the
  /// platform's own fixed-width face on Android and Linux.
  static const List<String> monoFallback = <String>[
    'Menlo',
    'Consolas',
    'Liberation Mono',
    'monospace',
  ];

  /// [mono] and [monoFallback] as a style to merge onto a [KunText] step:
  /// `KunText.sm.merge(KunFontFamilies.monoStyle)`.
  static const TextStyle monoStyle = TextStyle(
    fontFamily: mono,
    fontFamilyFallback: monoFallback,
  );
}
