<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from '#imports'
import { useKunMessage, type KunDropdownItem } from '@kungal/ui-vue'
import { site } from '~/site.config'

// "Copy page" control — the AI-friendly pattern from Mintlify/Anthropic/Vercel
// docs. Every route has a clean Markdown twin at `<route>.md` (generated by
// scripts/gen-page-md.mjs); this offers to copy it, copy its link, view it, or
// open it in ChatGPT / Claude. Dogfoods KunDropdown / KunButton / KunIcon.
const route = useRoute()

// "/components/button" → "/components/button.md" ; "/" → "/index.md"
const mdPath = computed(() => {
  const p = route.path.replace(/\/+$/, '')
  return p === '' ? '/index.md' : `${p}.md`
})
const mdUrl = computed(() => `${site.url}${mdPath.value}`)
const aiPrompt = () =>
  `阅读 ${mdUrl.value} —— 这是 KunUI 文档页面的 Markdown,我想基于它向你提问。`

const items: KunDropdownItem[] = [
  { key: 'copy', label: '复制本页 Markdown', icon: 'lucide:clipboard-copy' },
  { key: 'link', label: '复制 Markdown 链接', icon: 'lucide:link' },
  { key: 'view', label: '查看 Markdown', icon: 'lucide:file-text' },
  { key: 'chatgpt', label: '在 ChatGPT 中打开', icon: 'lucide:bot' },
  { key: 'claude', label: '在 Claude 中打开', icon: 'lucide:sparkles' },
]

const openExternal = (url: string) =>
  window.open(url, '_blank', 'noopener')

async function copy(text: string, ok: string) {
  try {
    await navigator.clipboard.writeText(text)
    useKunMessage(ok, 'success')
  } catch {
    useKunMessage('复制失败,请重试', 'error')
  }
}

async function onSelect(item: KunDropdownItem) {
  switch (item.key) {
    case 'copy': {
      try {
        const md = await fetch(mdPath.value).then((r) => r.text())
        await copy(md, '已复制本页 Markdown')
      } catch {
        useKunMessage('获取 Markdown 失败', 'error')
      }
      break
    }
    case 'link':
      await copy(mdUrl.value, '已复制 Markdown 链接')
      break
    case 'view':
      openExternal(mdPath.value)
      break
    case 'chatgpt':
      openExternal(`https://chatgpt.com/?q=${encodeURIComponent(aiPrompt())}`)
      break
    case 'claude':
      openExternal(`https://claude.ai/new?q=${encodeURIComponent(aiPrompt())}`)
      break
  }
}
</script>

<template>
  <KunDropdown :items="items" position="bottom-end" @select="onSelect">
    <template #trigger>
      <KunButton variant="bordered" color="default" size="sm">
        <KunIcon name="lucide:clipboard-copy" />
        <span class="hidden sm:inline">复制页面</span>
        <KunIcon name="lucide:chevron-down" class="opacity-60" />
      </KunButton>
    </template>
  </KunDropdown>
</template>
