// AUTO-GENERATED by packages/ui-core/scripts/gen-messages-flutter.mjs —
// do not edit. Source: packages/ui-core/src/locale/*.json, the same
// catalogs the web bundle resolves its strings from.

/// Every user-visible string KunUI renders on its own — accessible names
/// for icon-only controls, empty and loading states, and the handful of
/// built-in button labels.
///
/// A widget parameter that sets the same text always wins over the catalog;
/// the catalog is what the parameter falls back to.
library;

/// Strings for `KunAlert`.
class KunAlertStrings {
  const KunAlertStrings({
    required this.title,
    required this.confirm,
    required this.cancel,
  });

  /// `en`: Confirm
  final String title;

  /// `en`: OK
  final String confirm;

  /// `en`: Cancel
  final String cancel;
}

/// Strings for `KunAutocomplete`.
class KunAutocompleteStrings {
  const KunAutocompleteStrings({
    required this.clear,
    required this.loading,
    required this.noResult,
  });

  /// `en`: Clear
  final String clear;

  /// `en`: Loading…
  final String loading;

  /// `en`: No matching options
  final String noResult;
}

/// Strings for `KunAvatar`.
class KunAvatarStrings {
  const KunAvatarStrings({
    required this.unknownUser,
  });

  /// `en`: Unknown user
  final String unknownUser;
}

/// Strings for `KunAvatarGroup`.
class KunAvatarGroupStrings {
  const KunAvatarGroupStrings({
    required String label,
  }) : _label = label;

  final String _label;

  /// `en`: {count} users
  String label({required Object count}) =>
      _label.replaceAll('{count}', '$count');
}

/// Strings for `KunBanner`.
class KunBannerStrings {
  const KunBannerStrings({
    required this.label,
    required this.close,
  });

  /// `en`: Announcement
  final String label;

  /// `en`: Dismiss announcement
  final String close;
}

/// Strings for `KunCarousel`.
class KunCarouselStrings {
  const KunCarouselStrings({
    required this.label,
    required this.prev,
    required this.next,
    required this.nav,
    required String goto,
  }) : _goto = goto;

  /// `en`: Carousel
  final String label;

  /// `en`: Previous slide
  final String prev;

  /// `en`: Next slide
  final String next;

  /// `en`: Carousel navigation
  final String nav;

  final String _goto;

  /// `en`: Go to slide {index}
  String goto({required Object index}) => _goto.replaceAll('{index}', '$index');
}

/// Strings for `KunChat`.
class KunChatStrings {
  const KunChatStrings({
    required this.deletedUser,
    required this.you,
    required String senderPrefix,
    required this.today,
    required this.yesterday,
    required this.unreadDivider,
    required this.edited,
    required this.deletedMessage,
    required this.photo,
    required String album,
    required this.media,
    required this.draft,
    required this.messages,
    required this.empty,
    required this.loading,
    required this.scrollToBottom,
    required String scrollToBottomUnread,
    required String unreadCount,
    required this.mentioned,
    required this.pinned,
    required this.muted,
    required String photoFrom,
    required String openLink,
    required this.reactions,
    required String reactionCount,
    required this.back,
    required String members,
  })  : _senderPrefix = senderPrefix,
        _album = album,
        _scrollToBottomUnread = scrollToBottomUnread,
        _unreadCount = unreadCount,
        _photoFrom = photoFrom,
        _openLink = openLink,
        _reactionCount = reactionCount,
        _members = members;

  /// `en`: Deleted account
  final String deletedUser;

  /// `en`: You
  final String you;

  /// `en`: Today
  final String today;

  /// `en`: Yesterday
  final String yesterday;

  /// `en`: Unread messages
  final String unreadDivider;

  /// `en`: edited
  final String edited;

  /// `en`: Deleted message
  final String deletedMessage;

  /// `en`: Photo
  final String photo;

  /// `en`: Media
  final String media;

  /// `en`: Draft:
  final String draft;

  /// `en`: Messages
  final String messages;

  /// `en`: No messages yet
  final String empty;

  /// `en`: Loading…
  final String loading;

  /// `en`: Scroll to bottom
  final String scrollToBottom;

  /// `en`: You were mentioned
  final String mentioned;

  /// `en`: Pinned
  final String pinned;

  /// `en`: Muted
  final String muted;

  /// `en`: Reactions
  final String reactions;

  /// `en`: Back
  final String back;

  final String _senderPrefix;

  final String _album;

  final String _scrollToBottomUnread;

  final String _unreadCount;

  final String _photoFrom;

  final String _openLink;

  final String _reactionCount;

  final String _members;

  /// `en`: {name}:
  String senderPrefix({required Object name}) =>
      _senderPrefix.replaceAll('{name}', '$name');

  /// `en`: {count} photos
  String album({required Object count}) =>
      _album.replaceAll('{count}', '$count');

  /// `en`: Scroll to bottom, {count} new messages
  String scrollToBottomUnread({required Object count}) =>
      _scrollToBottomUnread.replaceAll('{count}', '$count');

  /// `en`: {count} unread messages
  String unreadCount({required Object count}) =>
      _unreadCount.replaceAll('{count}', '$count');

  /// `en`: Photo from {name}
  String photoFrom({required Object name}) =>
      _photoFrom.replaceAll('{name}', '$name');

  /// `en`: Open link {url}
  String openLink({required Object url}) =>
      _openLink.replaceAll('{url}', '$url');

  /// `en`: {label}, {count}
  String reactionCount({required Object label, required Object count}) =>
      _reactionCount
          .replaceAll('{label}', '$label')
          .replaceAll('{count}', '$count');

  /// `en`: {count} members
  String members({required Object count}) =>
      _members.replaceAll('{count}', '$count');
}

/// Strings for `KunChatComposer`.
class KunChatComposerStrings {
  const KunChatComposerStrings({
    required this.placeholder,
    required this.send,
    required this.save,
    required this.attach,
    required this.removeAttachment,
    required this.retryAttachment,
    required String replyTo,
    required String quoteFrom,
    required this.editing,
    required this.cancelReply,
    required this.cancelEdit,
    required String remaining,
    required String overLimit,
    required this.dropHint,
  })  : _replyTo = replyTo,
        _quoteFrom = quoteFrom,
        _remaining = remaining,
        _overLimit = overLimit;

  /// `en`: Message…
  final String placeholder;

  /// `en`: Send
  final String send;

  /// `en`: Save
  final String save;

  /// `en`: Add photos
  final String attach;

  /// `en`: Remove attachment
  final String removeAttachment;

  /// `en`: Upload failed, tap to retry
  final String retryAttachment;

  /// `en`: Edit message
  final String editing;

  /// `en`: Cancel reply
  final String cancelReply;

  /// `en`: Cancel editing
  final String cancelEdit;

  /// `en`: Drop to add photos
  final String dropHint;

  final String _replyTo;

  final String _quoteFrom;

  final String _remaining;

  final String _overLimit;

  /// `en`: Reply to {name}
  String replyTo({required Object name}) =>
      _replyTo.replaceAll('{name}', '$name');

  /// `en`: Quote from {name}
  String quoteFrom({required Object name}) =>
      _quoteFrom.replaceAll('{name}', '$name');

  /// `en`: {count} characters left
  String remaining({required Object count}) =>
      _remaining.replaceAll('{count}', '$count');

  /// `en`: {count} characters over the limit
  String overLimit({required Object count}) =>
      _overLimit.replaceAll('{count}', '$count');
}

/// Strings for `KunChatMenu`.
class KunChatMenuStrings {
  const KunChatMenuStrings({
    required this.label,
    required this.reply,
    required this.quote,
    required this.copy,
    required this.copied,
    required this.edit,
    required this.pin,
    required this.unpin,
    required this.delete,
    required this.report,
    required this.retry,
    required this.moreReactions,
    required this.fewerReactions,
  });

  /// `en`: Message actions
  final String label;

  /// `en`: Reply
  final String reply;

  /// `en`: Quote
  final String quote;

  /// `en`: Copy
  final String copy;

  /// `en`: Copied
  final String copied;

  /// `en`: Edit
  final String edit;

  /// `en`: Pin
  final String pin;

  /// `en`: Unpin
  final String unpin;

  /// `en`: Delete
  final String delete;

  /// `en`: Report
  final String report;

  /// `en`: Resend
  final String retry;

  /// `en`: More reactions
  final String moreReactions;

  /// `en`: Fewer reactions
  final String fewerReactions;
}

/// Strings for `KunChatPinned`.
class KunChatPinnedStrings {
  const KunChatPinnedStrings({
    required this.label,
    required String indexed,
    required this.unpin,
  }) : _indexed = indexed;

  /// `en`: Pinned message
  final String label;

  /// `en`: Unpin
  final String unpin;

  final String _indexed;

  /// `en`: Pinned message #{index}
  String indexed({required Object index}) =>
      _indexed.replaceAll('{index}', '$index');
}

/// Strings for `KunChatRequest`.
class KunChatRequestStrings {
  const KunChatRequestStrings({
    required this.title,
    required String description,
    required this.accept,
    required this.delete,
    required this.block,
    required this.report,
  }) : _description = description;

  /// `en`: Message request
  final String title;

  /// `en`: Accept
  final String accept;

  /// `en`: Delete
  final String delete;

  /// `en`: Block
  final String block;

  /// `en`: Report
  final String report;

  final String _description;

  /// `en`: {name} wants to message you. Until you accept, they can't see whether you've read it.
  String description({required Object name}) =>
      _description.replaceAll('{name}', '$name');
}

/// Strings for `KunChatService`.
class KunChatServiceStrings {
  const KunChatServiceStrings({
    required String groupCreated,
    required String groupCreatedTitled,
    required String membersAdded,
    required String memberJoined,
    required String memberLeft,
    required String memberRemoved,
    required String titleChanged,
    required String photoChanged,
    required String messagePinned,
    required String messagePinnedMedia,
    required String joinedByLink,
  })  : _groupCreated = groupCreated,
        _groupCreatedTitled = groupCreatedTitled,
        _membersAdded = membersAdded,
        _memberJoined = memberJoined,
        _memberLeft = memberLeft,
        _memberRemoved = memberRemoved,
        _titleChanged = titleChanged,
        _photoChanged = photoChanged,
        _messagePinned = messagePinned,
        _messagePinnedMedia = messagePinnedMedia,
        _joinedByLink = joinedByLink;

  final String _groupCreated;

  final String _groupCreatedTitled;

  final String _membersAdded;

  final String _memberJoined;

  final String _memberLeft;

  final String _memberRemoved;

  final String _titleChanged;

  final String _photoChanged;

  final String _messagePinned;

  final String _messagePinnedMedia;

  final String _joinedByLink;

  /// `en`: {actor} created the group
  String groupCreated({required Object actor}) =>
      _groupCreated.replaceAll('{actor}', '$actor');

  /// `en`: {actor} created the group “{title}”
  String groupCreatedTitled({required Object actor, required Object title}) =>
      _groupCreatedTitled
          .replaceAll('{actor}', '$actor')
          .replaceAll('{title}', '$title');

  /// `en`: {actor} added {users}
  String membersAdded({required Object actor, required Object users}) =>
      _membersAdded
          .replaceAll('{actor}', '$actor')
          .replaceAll('{users}', '$users');

  /// `en`: {actor} joined the group
  String memberJoined({required Object actor}) =>
      _memberJoined.replaceAll('{actor}', '$actor');

  /// `en`: {actor} left the group
  String memberLeft({required Object actor}) =>
      _memberLeft.replaceAll('{actor}', '$actor');

  /// `en`: {actor} removed {user}
  String memberRemoved({required Object actor, required Object user}) =>
      _memberRemoved
          .replaceAll('{actor}', '$actor')
          .replaceAll('{user}', '$user');

  /// `en`: {actor} renamed the group to “{title}”
  String titleChanged({required Object actor, required Object title}) =>
      _titleChanged
          .replaceAll('{actor}', '$actor')
          .replaceAll('{title}', '$title');

  /// `en`: {actor} changed the group photo
  String photoChanged({required Object actor}) =>
      _photoChanged.replaceAll('{actor}', '$actor');

  /// `en`: {actor} pinned “{text}”
  String messagePinned({required Object actor, required Object text}) =>
      _messagePinned
          .replaceAll('{actor}', '$actor')
          .replaceAll('{text}', '$text');

  /// `en`: {actor} pinned a message
  String messagePinnedMedia({required Object actor}) =>
      _messagePinnedMedia.replaceAll('{actor}', '$actor');

  /// `en`: {actor} joined via invite link
  String joinedByLink({required Object actor}) =>
      _joinedByLink.replaceAll('{actor}', '$actor');
}

/// Strings for `KunChatStatus`.
class KunChatStatusStrings {
  const KunChatStatusStrings({
    required this.sending,
    required this.sent,
    required this.read,
    required this.failed,
  });

  /// `en`: Sending
  final String sending;

  /// `en`: Sent
  final String sent;

  /// `en`: Read
  final String read;

  /// `en`: Not sent, tap to retry
  final String failed;
}

/// Strings for `KunChatTyping`.
class KunChatTypingStrings {
  const KunChatTypingStrings({
    required this.typing,
    required String one,
    required String several,
    required String many,
  })  : _one = one,
        _several = several,
        _many = many;

  /// `en`: typing…
  final String typing;

  final String _one;

  final String _several;

  final String _many;

  /// `en`: {name} is typing…
  String one({required Object name}) => _one.replaceAll('{name}', '$name');

  /// `en`: {names} are typing…
  String several({required Object names}) =>
      _several.replaceAll('{names}', '$names');

  /// `en`: {name} and {count} others are typing…
  String many({required Object name, required Object count}) =>
      _many.replaceAll('{name}', '$name').replaceAll('{count}', '$count');
}

/// Strings for `KunChip`.
class KunChipStrings {
  const KunChipStrings({
    required this.remove,
  });

  /// `en`: Remove
  final String remove;
}

/// Strings for `KunCommandPalette`.
class KunCommandPaletteStrings {
  const KunCommandPaletteStrings({
    required this.placeholder,
    required this.empty,
    required this.noResult,
    required this.loading,
    required this.close,
    required this.hintSelect,
    required this.hintOpen,
    required this.hintClose,
    required String resultCount,
  }) : _resultCount = resultCount;

  /// `en`: Search…
  final String placeholder;

  /// `en`: Type to search
  final String empty;

  /// `en`: No results
  final String noResult;

  /// `en`: Loading…
  final String loading;

  /// `en`: Close
  final String close;

  /// `en`: Select
  final String hintSelect;

  /// `en`: Open
  final String hintOpen;

  /// `en`: Close
  final String hintClose;

  final String _resultCount;

  /// `en`: {count} results
  String resultCount({required Object count}) =>
      _resultCount.replaceAll('{count}', '$count');
}

/// Strings for `KunCopy`.
class KunCopyStrings {
  const KunCopyStrings({
    required this.copied,
    required String success,
    required String failure,
  })  : _success = success,
        _failure = failure;

  /// `en`: Copied
  final String copied;

  final String _success;

  final String _failure;

  /// `en`: Copied {text}
  String success({required Object text}) =>
      _success.replaceAll('{text}', '$text');

  /// `en`: Could not copy {text} — your browser blocked clipboard access.
  String failure({required Object text}) =>
      _failure.replaceAll('{text}', '$text');
}

/// Strings for `KunDatePicker`.
class KunDatePickerStrings {
  const KunDatePickerStrings({
    required this.placeholderDay,
    required this.placeholderMonth,
    required this.placeholderYear,
    required this.clear,
    required this.today,
    required this.close,
    required this.prevYear,
    required this.nextYear,
    required String prevPage,
    required String nextPage,
    required String zoomOut,
    required this.unitMonth,
    required this.unitYear,
    required this.unitDecade,
    required String monthCell,
  })  : _prevPage = prevPage,
        _nextPage = nextPage,
        _zoomOut = zoomOut,
        _monthCell = monthCell;

  /// `en`: Select a date
  final String placeholderDay;

  /// `en`: Select a month
  final String placeholderMonth;

  /// `en`: Select a year
  final String placeholderYear;

  /// `en`: Clear
  final String clear;

  /// `en`: Today
  final String today;

  /// `en`: Close
  final String close;

  /// `en`: Previous year
  final String prevYear;

  /// `en`: Next year
  final String nextYear;

  /// `en`: month
  final String unitMonth;

  /// `en`: year
  final String unitYear;

  /// `en`: decade
  final String unitDecade;

  final String _prevPage;

  final String _nextPage;

  final String _zoomOut;

  final String _monthCell;

  /// `en`: Previous {unit}
  String prevPage({required Object unit}) =>
      _prevPage.replaceAll('{unit}', '$unit');

  /// `en`: Next {unit}
  String nextPage({required Object unit}) =>
      _nextPage.replaceAll('{unit}', '$unit');

  /// `en`: {label} — zoom out
  String zoomOut({required Object label}) =>
      _zoomOut.replaceAll('{label}', '$label');

  /// `en`: {month} {year}
  String monthCell({required Object year, required Object month}) =>
      _monthCell.replaceAll('{year}', '$year').replaceAll('{month}', '$month');
}

/// Strings for `KunDrawer`.
class KunDrawerStrings {
  const KunDrawerStrings({
    required this.close,
  });

  /// `en`: Close drawer
  final String close;
}

/// Strings for `KunFileInput`.
class KunFileInputStrings {
  const KunFileInputStrings({
    required this.trigger,
    required String selected,
  }) : _selected = selected;

  /// `en`: Choose files
  final String trigger;

  final String _selected;

  /// `en`: {count} files selected
  String selected({required Object count}) =>
      _selected.replaceAll('{count}', '$count');
}

/// Strings for `KunFilePicker`.
class KunFilePickerStrings {
  const KunFilePickerStrings({
    required String tooLarge,
  }) : _tooLarge = tooLarge;

  final String _tooLarge;

  /// `en`: {name} exceeds the {size} size limit
  String tooLarge({required Object name, required Object size}) =>
      _tooLarge.replaceAll('{name}', '$name').replaceAll('{size}', '$size');
}

/// Strings for `KunInput`.
class KunInputStrings {
  const KunInputStrings({
    required this.clear,
    required this.reveal,
    required this.hide,
  });

  /// `en`: Clear
  final String clear;

  /// `en`: Show password
  final String reveal;

  /// `en`: Hide password
  final String hide;
}

/// Strings for `KunKbd`.
class KunKbdStrings {
  const KunKbdStrings({
    required this.control,
    required this.alt,
    required this.option,
    required this.shift,
    required this.command,
    required this.meta,
    required this.enter,
    required this.escape,
    required this.backspace,
    required this.delete,
    required this.tab,
    required this.space,
    required this.up,
    required this.down,
    required this.left,
    required this.right,
    required this.pageUp,
    required this.pageDown,
    required this.home,
    required this.end,
    required this.plus,
    required this.then,
  });

  /// `en`: Control
  final String control;

  /// `en`: Alt
  final String alt;

  /// `en`: Option
  final String option;

  /// `en`: Shift
  final String shift;

  /// `en`: Command
  final String command;

  /// `en`: Windows
  final String meta;

  /// `en`: Enter
  final String enter;

  /// `en`: Escape
  final String escape;

  /// `en`: Backspace
  final String backspace;

  /// `en`: Delete
  final String delete;

  /// `en`: Tab
  final String tab;

  /// `en`: Space
  final String space;

  /// `en`: Up Arrow
  final String up;

  /// `en`: Down Arrow
  final String down;

  /// `en`: Left Arrow
  final String left;

  /// `en`: Right Arrow
  final String right;

  /// `en`: Page Up
  final String pageUp;

  /// `en`: Page Down
  final String pageDown;

  /// `en`: Home
  final String home;

  /// `en`: End
  final String end;

  /// `en`: Plus
  final String plus;

  /// `en`: then
  final String then;
}

/// Strings for `KunLightbox`.
class KunLightboxStrings {
  const KunLightboxStrings({
    required this.label,
    required this.close,
    required this.prev,
    required this.next,
    required String goto,
    required this.zoomIn,
    required this.zoomOut,
    required this.rotateLeft,
    required this.rotateRight,
    required this.reset,
    required this.download,
  }) : _goto = goto;

  /// `en`: Image viewer
  final String label;

  /// `en`: Close
  final String close;

  /// `en`: Previous image
  final String prev;

  /// `en`: Next image
  final String next;

  /// `en`: Zoom in
  final String zoomIn;

  /// `en`: Zoom out
  final String zoomOut;

  /// `en`: Rotate 90° left
  final String rotateLeft;

  /// `en`: Rotate 90° right
  final String rotateRight;

  /// `en`: Reset zoom, rotation and position
  final String reset;

  /// `en`: Download
  final String download;

  final String _goto;

  /// `en`: Go to image {index}
  String goto({required Object index}) => _goto.replaceAll('{index}', '$index');
}

/// Strings for `KunLightboxGallery`.
class KunLightboxGalleryStrings {
  const KunLightboxGalleryStrings({
    required this.view,
  });

  /// `en`: View full size
  final String view;
}

/// Strings for `KunLoading`.
class KunLoadingStrings {
  const KunLoadingStrings({
    required this.description,
  });

  /// `en`: Loading…
  final String description;
}

/// Strings for `KunLoli`.
class KunLoliStrings {
  const KunLoliStrings({
    required this.close,
  });

  /// `en`: Close
  final String close;
}

/// Strings for `KunMessage`.
class KunMessageStrings {
  const KunMessageStrings({
    required this.close,
  });

  /// `en`: Close
  final String close;
}

/// Strings for `KunModal`.
class KunModalStrings {
  const KunModalStrings({
    required this.close,
  });

  /// `en`: Close
  final String close;
}

/// Strings for `KunNullState`.
///
/// Reached as `messages.nullState`: the web namespace is
/// `null`, which is a Dart reserved word.
class KunNullStateStrings {
  const KunNullStateStrings({
    required this.description,
  });

  /// `en`: Nothing here yet
  final String description;
}

/// Strings for `KunNumberInput`.
class KunNumberInputStrings {
  const KunNumberInputStrings({
    required this.decrement,
    required this.increment,
  });

  /// `en`: Decrease
  final String decrement;

  /// `en`: Increase
  final String increment;
}

/// Strings for `KunPagination`.
class KunPaginationStrings {
  const KunPaginationStrings({
    required this.nav,
    required this.prev,
    required this.next,
    required String page,
    required this.hintBefore,
    required this.hintAfter,
    required this.jumpLabel,
    required this.jump,
  }) : _page = page;

  /// `en`: Pagination
  final String nav;

  /// `en`: Previous page
  final String prev;

  /// `en`: Next page
  final String next;

  /// `en`: Use
  final String hintBefore;

  /// `en`: to turn pages quickly
  final String hintAfter;

  /// `en`: Go to page
  final String jumpLabel;

  /// `en`: Go
  final String jump;

  final String _page;

  /// `en`: Page {page}
  String page({required Object page}) => _page.replaceAll('{page}', '$page');
}

/// Strings for `KunPinInput`.
class KunPinInputStrings {
  const KunPinInputStrings({
    required this.label,
    required String digit,
  }) : _digit = digit;

  /// `en`: Verification code
  final String label;

  final String _digit;

  /// `en`: {label} digit {index}
  String digit({required Object label, required Object index}) =>
      _digit.replaceAll('{label}', '$label').replaceAll('{index}', '$index');
}

/// Strings for `KunReaction`.
class KunReactionStrings {
  const KunReactionStrings({
    required this.label,
  });

  /// `en`: Like
  final String label;
}

/// Strings for `KunSelect`.
class KunSelectStrings {
  const KunSelectStrings({
    required this.searchPlaceholder,
    required this.noResult,
    required this.loading,
    required this.clear,
    required String removeOption,
  }) : _removeOption = removeOption;

  /// `en`: Search…
  final String searchPlaceholder;

  /// `en`: No matching options
  final String noResult;

  /// `en`: Loading…
  final String loading;

  /// `en`: Clear
  final String clear;

  final String _removeOption;

  /// `en`: Remove {label}
  String removeOption({required Object label}) =>
      _removeOption.replaceAll('{label}', '$label');
}

/// Strings for `KunSpoiler`.
class KunSpoilerStrings {
  const KunSpoilerStrings({
    required this.copyCode,
    required this.reveal,
  });

  /// `en`: Copy code
  final String copyCode;

  /// `en`: Spoiler — click or press Enter to reveal
  final String reveal;
}

/// Strings for `KunSteps`.
class KunStepsStrings {
  const KunStepsStrings({
    required String completed,
    required String current,
    required String pending,
    required String error,
  })  : _completed = completed,
        _current = current,
        _pending = pending,
        _error = error;

  final String _completed;

  final String _current;

  final String _pending;

  final String _error;

  /// `en`: Completed: {title}
  String completed({required Object title}) =>
      _completed.replaceAll('{title}', '$title');

  /// `en`: Current step: {title}
  String current({required Object title}) =>
      _current.replaceAll('{title}', '$title');

  /// `en`: Not started: {title}
  String pending({required Object title}) =>
      _pending.replaceAll('{title}', '$title');

  /// `en`: Error: {title}
  String error({required Object title}) =>
      _error.replaceAll('{title}', '$title');
}

/// Strings for `KunTagInput`.
class KunTagInputStrings {
  const KunTagInputStrings({
    required String tag,
    required String removeTag,
  })  : _tag = tag,
        _removeTag = removeTag;

  final String _tag;

  final String _removeTag;

  /// `en`: Tag {tag}
  String tag({required Object tag}) => _tag.replaceAll('{tag}', '$tag');

  /// `en`: Remove tag {tag}
  String removeTag({required Object tag}) =>
      _removeTag.replaceAll('{tag}', '$tag');
}

/// Strings for `KunTextSelection`.
class KunTextSelectionStrings {
  const KunTextSelectionStrings({
    required this.copy,
    required this.cut,
    required this.paste,
    required this.selectAll,
    required this.share,
    required this.lookUp,
    required this.searchWeb,
  });

  /// `en`: Copy
  final String copy;

  /// `en`: Cut
  final String cut;

  /// `en`: Paste
  final String paste;

  /// `en`: Select all
  final String selectAll;

  /// `en`: Share
  final String share;

  /// `en`: Look Up
  final String lookUp;

  /// `en`: Search Web
  final String searchWeb;
}

/// Strings for `KunUpload`.
class KunUploadStrings {
  const KunUploadStrings({
    required this.imageAlt,
    required this.cropTitle,
    required this.cancel,
    required this.confirm,
  });

  /// `en`: Uploaded image
  final String imageAlt;

  /// `en`: Crop image
  final String cropTitle;

  /// `en`: Cancel
  final String cancel;

  /// `en`: OK
  final String confirm;
}

/// A complete KunUI message catalog.
///
/// ```dart
/// const messages = KunMessages.zhCN;
/// Semantics(label: messages.input.clear, child: …);
/// Text(messages.pagination.page(page: 3));
/// ```
///
/// A string with a `{placeholder}` is a method with required named
/// parameters, not a field: the whole template is one string because a
/// value moves position between languages, and requiring the parameters
/// means a missing one is a compile error instead of a literal `{month}`
/// in an accessibility label.
class KunMessages {
  const KunMessages({
    required this.name,
    required this.code,
    required this.alert,
    required this.autocomplete,
    required this.avatar,
    required this.avatarGroup,
    required this.banner,
    required this.carousel,
    required this.chat,
    required this.chatComposer,
    required this.chatMenu,
    required this.chatPinned,
    required this.chatRequest,
    required this.chatService,
    required this.chatStatus,
    required this.chatTyping,
    required this.chip,
    required this.commandPalette,
    required this.copy,
    required this.datePicker,
    required this.drawer,
    required this.fileInput,
    required this.filePicker,
    required this.input,
    required this.kbd,
    required this.lightbox,
    required this.lightboxGallery,
    required this.loading,
    required this.loli,
    required this.message,
    required this.modal,
    required this.nullState,
    required this.numberInput,
    required this.pagination,
    required this.pinInput,
    required this.reaction,
    required this.select,
    required this.spoiler,
    required this.steps,
    required this.tagInput,
    required this.textSelection,
    required this.upload,
  });

  /// Endonym, for a language switcher's own list (e.g. `简体中文`).
  final String name;

  /// BCP 47 tag. KunUI never picks a locale for you; this is what a
  /// `KunDatePicker` resolves its calendar grid from when you do.
  final String code;

  final KunAlertStrings alert;

  final KunAutocompleteStrings autocomplete;

  final KunAvatarStrings avatar;

  final KunAvatarGroupStrings avatarGroup;

  final KunBannerStrings banner;

  final KunCarouselStrings carousel;

  final KunChatStrings chat;

  final KunChatComposerStrings chatComposer;

  final KunChatMenuStrings chatMenu;

  final KunChatPinnedStrings chatPinned;

  final KunChatRequestStrings chatRequest;

  final KunChatServiceStrings chatService;

  final KunChatStatusStrings chatStatus;

  final KunChatTypingStrings chatTyping;

  final KunChipStrings chip;

  final KunCommandPaletteStrings commandPalette;

  final KunCopyStrings copy;

  final KunDatePickerStrings datePicker;

  final KunDrawerStrings drawer;

  final KunFileInputStrings fileInput;

  final KunFilePickerStrings filePicker;

  final KunInputStrings input;

  final KunKbdStrings kbd;

  final KunLightboxStrings lightbox;

  final KunLightboxGalleryStrings lightboxGallery;

  final KunLoadingStrings loading;

  final KunLoliStrings loli;

  final KunMessageStrings message;

  final KunModalStrings modal;

  final KunNullStateStrings nullState;

  final KunNumberInputStrings numberInput;

  final KunPaginationStrings pagination;

  final KunPinInputStrings pinInput;

  final KunReactionStrings reaction;

  final KunSelectStrings select;

  final KunSpoilerStrings spoiler;

  final KunStepsStrings steps;

  final KunTagInputStrings tagInput;

  final KunTextSelectionStrings textSelection;

  final KunUploadStrings upload;

  /// 简体中文 (`zh-CN`).
  static const KunMessages zhCN = KunMessages(
    name: '简体中文',
    code: 'zh-CN',
    alert: KunAlertStrings(
      title: '确认',
      confirm: '确定',
      cancel: '取消',
    ),
    autocomplete: KunAutocompleteStrings(
      clear: '清除',
      loading: '加载中…',
      noResult: '无匹配项',
    ),
    avatar: KunAvatarStrings(
      unknownUser: '未知用户',
    ),
    avatarGroup: KunAvatarGroupStrings(
      label: '{count} 位用户',
    ),
    banner: KunBannerStrings(
      label: '公告',
      close: '关闭公告',
    ),
    carousel: KunCarouselStrings(
      label: '轮播',
      prev: '上一张',
      next: '下一张',
      nav: '轮播导航',
      goto: '跳到第 {index} 张',
    ),
    chat: KunChatStrings(
      deletedUser: '已注销用户',
      you: '你',
      senderPrefix: '{name}：',
      today: '今天',
      yesterday: '昨天',
      unreadDivider: '以下为未读消息',
      edited: '已编辑',
      deletedMessage: '消息已删除',
      photo: '图片',
      album: '{count} 张图片',
      media: '媒体',
      draft: '草稿：',
      messages: '消息',
      empty: '还没有消息',
      loading: '加载中…',
      scrollToBottom: '回到底部',
      scrollToBottomUnread: '回到底部，{count} 条新消息',
      unreadCount: '{count} 条未读消息',
      mentioned: '有人提到了你',
      pinned: '已置顶',
      muted: '已静音',
      photoFrom: '{name} 发送的图片',
      openLink: '打开链接 {url}',
      reactions: '回应',
      reactionCount: '{label}，{count} 人',
      back: '返回',
      members: '{count} 位成员',
    ),
    chatComposer: KunChatComposerStrings(
      placeholder: '发消息…',
      send: '发送',
      save: '保存',
      attach: '添加图片',
      removeAttachment: '移除附件',
      retryAttachment: '上传失败，点击重试',
      replyTo: '回复 {name}',
      quoteFrom: '引用 {name}',
      editing: '编辑消息',
      cancelReply: '取消回复',
      cancelEdit: '取消编辑',
      remaining: '还可输入 {count} 字',
      overLimit: '超出 {count} 字',
      dropHint: '松开以添加图片',
    ),
    chatMenu: KunChatMenuStrings(
      label: '消息操作',
      reply: '回复',
      quote: '引用',
      copy: '复制',
      copied: '已复制',
      edit: '编辑',
      pin: '置顶',
      unpin: '取消置顶',
      delete: '删除',
      report: '举报',
      retry: '重新发送',
      moreReactions: '更多回应',
      fewerReactions: '收起回应',
    ),
    chatPinned: KunChatPinnedStrings(
      label: '置顶消息',
      indexed: '置顶消息 #{index}',
      unpin: '取消置顶',
    ),
    chatRequest: KunChatRequestStrings(
      title: '消息请求',
      description: '{name} 想给你发消息。接受之前，对方看不到你是否已读。',
      accept: '接受',
      delete: '删除',
      block: '拉黑',
      report: '举报',
    ),
    chatService: KunChatServiceStrings(
      groupCreated: '{actor} 创建了群组',
      groupCreatedTitled: '{actor} 创建了群组「{title}」',
      membersAdded: '{actor} 邀请了 {users}',
      memberJoined: '{actor} 加入了群组',
      memberLeft: '{actor} 退出了群组',
      memberRemoved: '{actor} 将 {user} 移出了群组',
      titleChanged: '{actor} 将群名改为「{title}」',
      photoChanged: '{actor} 更换了群头像',
      messagePinned: '{actor} 置顶了「{text}」',
      messagePinnedMedia: '{actor} 置顶了一条消息',
      joinedByLink: '{actor} 通过邀请链接加入了群组',
    ),
    chatStatus: KunChatStatusStrings(
      sending: '发送中',
      sent: '已发送',
      read: '已读',
      failed: '发送失败，点击重试',
    ),
    chatTyping: KunChatTypingStrings(
      typing: '正在输入…',
      one: '{name} 正在输入…',
      several: '{names} 正在输入…',
      many: '{name} 等 {count} 人正在输入…',
    ),
    chip: KunChipStrings(
      remove: '移除',
    ),
    commandPalette: KunCommandPaletteStrings(
      placeholder: '搜索…',
      empty: '输入关键字搜索',
      noResult: '无结果',
      loading: '加载中…',
      close: '关闭',
      hintSelect: '选择',
      hintOpen: '打开',
      hintClose: '关闭',
      resultCount: '{count} 条结果',
    ),
    copy: KunCopyStrings(
      copied: '已复制',
      success: '{text} 复制成功',
      failure: '{text} 复制失败! 请更换更现代的浏览器!',
    ),
    datePicker: KunDatePickerStrings(
      placeholderDay: '请选择日期',
      placeholderMonth: '请选择月份',
      placeholderYear: '请选择年份',
      clear: '清空',
      today: '今天',
      close: '关闭',
      prevYear: '上一年',
      nextYear: '下一年',
      prevPage: '上一{unit}',
      nextPage: '下一{unit}',
      zoomOut: '{label} — 返回上一级',
      unitMonth: '月',
      unitYear: '年',
      unitDecade: '个十年',
      monthCell: '{year}年{month}',
    ),
    drawer: KunDrawerStrings(
      close: '关闭抽屉',
    ),
    fileInput: KunFileInputStrings(
      trigger: '选择文件',
      selected: '已选 {count} 个文件',
    ),
    filePicker: KunFilePickerStrings(
      tooLarge: '{name} 超过大小限制 ({size})',
    ),
    input: KunInputStrings(
      clear: '清除',
      reveal: '显示密码',
      hide: '隐藏密码',
    ),
    kbd: KunKbdStrings(
      control: 'Ctrl',
      alt: 'Alt',
      option: 'Option',
      shift: 'Shift',
      command: 'Command',
      meta: 'Windows 键',
      enter: '回车',
      escape: 'Esc',
      backspace: '退格',
      delete: '删除',
      tab: 'Tab',
      space: '空格',
      up: '上箭头',
      down: '下箭头',
      left: '左箭头',
      right: '右箭头',
      pageUp: '向上翻页',
      pageDown: '向下翻页',
      home: 'Home',
      end: 'End',
      plus: '加号',
      then: '然后',
    ),
    lightbox: KunLightboxStrings(
      label: '图片查看器',
      close: '关闭',
      prev: '上一张',
      next: '下一张',
      goto: '跳转到第 {index} 张',
      zoomIn: '放大',
      zoomOut: '缩小',
      rotateLeft: '向左旋转 90°',
      rotateRight: '向右旋转 90°',
      reset: '重置缩放/旋转/位置',
      download: '下载',
    ),
    lightboxGallery: KunLightboxGalleryStrings(
      view: '查看大图',
    ),
    loading: KunLoadingStrings(
      description: '正在摸鱼中...咕咕咕',
    ),
    loli: KunLoliStrings(
      close: '关闭',
    ),
    message: KunMessageStrings(
      close: '关闭',
    ),
    modal: KunModalStrings(
      close: '关闭',
    ),
    nullState: KunNullStateStrings(
      description: '莲说这里什么都没有',
    ),
    numberInput: KunNumberInputStrings(
      decrement: '减少',
      increment: '增加',
    ),
    pagination: KunPaginationStrings(
      nav: '分页导航',
      prev: '上一页',
      next: '下一页',
      page: '第 {page} 页',
      hintBefore: '您可以使用',
      hintAfter: '来进行快速翻页',
      jumpLabel: '跳转到页数',
      jump: '跳转',
    ),
    pinInput: KunPinInputStrings(
      label: '验证码',
      digit: '{label} 第 {index} 位',
    ),
    reaction: KunReactionStrings(
      label: '点赞',
    ),
    select: KunSelectStrings(
      searchPlaceholder: '搜索…',
      noResult: '无匹配项',
      loading: '加载中…',
      clear: '清除',
      removeOption: '移除 {label}',
    ),
    spoiler: KunSpoilerStrings(
      copyCode: '复制代码',
      reveal: '剧透内容,点击或按回车显示',
    ),
    steps: KunStepsStrings(
      completed: '已完成：{title}',
      current: '当前步骤：{title}',
      pending: '未开始：{title}',
      error: '出错：{title}',
    ),
    tagInput: KunTagInputStrings(
      tag: '标签 {tag}',
      removeTag: '移除标签 {tag}',
    ),
    textSelection: KunTextSelectionStrings(
      copy: '复制',
      cut: '剪切',
      paste: '粘贴',
      selectAll: '全选',
      share: '分享',
      lookUp: '查询',
      searchWeb: '搜索',
    ),
    upload: KunUploadStrings(
      imageAlt: '上传图片',
      cropTitle: '裁剪图片',
      cancel: '取消',
      confirm: '确定',
    ),
  );

  /// English (`en`).
  static const KunMessages en = KunMessages(
    name: 'English',
    code: 'en',
    alert: KunAlertStrings(
      title: 'Confirm',
      confirm: 'OK',
      cancel: 'Cancel',
    ),
    autocomplete: KunAutocompleteStrings(
      clear: 'Clear',
      loading: 'Loading…',
      noResult: 'No matching options',
    ),
    avatar: KunAvatarStrings(
      unknownUser: 'Unknown user',
    ),
    avatarGroup: KunAvatarGroupStrings(
      label: '{count} users',
    ),
    banner: KunBannerStrings(
      label: 'Announcement',
      close: 'Dismiss announcement',
    ),
    carousel: KunCarouselStrings(
      label: 'Carousel',
      prev: 'Previous slide',
      next: 'Next slide',
      nav: 'Carousel navigation',
      goto: 'Go to slide {index}',
    ),
    chat: KunChatStrings(
      deletedUser: 'Deleted account',
      you: 'You',
      senderPrefix: '{name}: ',
      today: 'Today',
      yesterday: 'Yesterday',
      unreadDivider: 'Unread messages',
      edited: 'edited',
      deletedMessage: 'Deleted message',
      photo: 'Photo',
      album: '{count} photos',
      media: 'Media',
      draft: 'Draft: ',
      messages: 'Messages',
      empty: 'No messages yet',
      loading: 'Loading…',
      scrollToBottom: 'Scroll to bottom',
      scrollToBottomUnread: 'Scroll to bottom, {count} new messages',
      unreadCount: '{count} unread messages',
      mentioned: 'You were mentioned',
      pinned: 'Pinned',
      muted: 'Muted',
      photoFrom: 'Photo from {name}',
      openLink: 'Open link {url}',
      reactions: 'Reactions',
      reactionCount: '{label}, {count}',
      back: 'Back',
      members: '{count} members',
    ),
    chatComposer: KunChatComposerStrings(
      placeholder: 'Message…',
      send: 'Send',
      save: 'Save',
      attach: 'Add photos',
      removeAttachment: 'Remove attachment',
      retryAttachment: 'Upload failed, tap to retry',
      replyTo: 'Reply to {name}',
      quoteFrom: 'Quote from {name}',
      editing: 'Edit message',
      cancelReply: 'Cancel reply',
      cancelEdit: 'Cancel editing',
      remaining: '{count} characters left',
      overLimit: '{count} characters over the limit',
      dropHint: 'Drop to add photos',
    ),
    chatMenu: KunChatMenuStrings(
      label: 'Message actions',
      reply: 'Reply',
      quote: 'Quote',
      copy: 'Copy',
      copied: 'Copied',
      edit: 'Edit',
      pin: 'Pin',
      unpin: 'Unpin',
      delete: 'Delete',
      report: 'Report',
      retry: 'Resend',
      moreReactions: 'More reactions',
      fewerReactions: 'Fewer reactions',
    ),
    chatPinned: KunChatPinnedStrings(
      label: 'Pinned message',
      indexed: 'Pinned message #{index}',
      unpin: 'Unpin',
    ),
    chatRequest: KunChatRequestStrings(
      title: 'Message request',
      description:
          '{name} wants to message you. Until you accept, they can\'t see whether you\'ve read it.',
      accept: 'Accept',
      delete: 'Delete',
      block: 'Block',
      report: 'Report',
    ),
    chatService: KunChatServiceStrings(
      groupCreated: '{actor} created the group',
      groupCreatedTitled: '{actor} created the group “{title}”',
      membersAdded: '{actor} added {users}',
      memberJoined: '{actor} joined the group',
      memberLeft: '{actor} left the group',
      memberRemoved: '{actor} removed {user}',
      titleChanged: '{actor} renamed the group to “{title}”',
      photoChanged: '{actor} changed the group photo',
      messagePinned: '{actor} pinned “{text}”',
      messagePinnedMedia: '{actor} pinned a message',
      joinedByLink: '{actor} joined via invite link',
    ),
    chatStatus: KunChatStatusStrings(
      sending: 'Sending',
      sent: 'Sent',
      read: 'Read',
      failed: 'Not sent, tap to retry',
    ),
    chatTyping: KunChatTypingStrings(
      typing: 'typing…',
      one: '{name} is typing…',
      several: '{names} are typing…',
      many: '{name} and {count} others are typing…',
    ),
    chip: KunChipStrings(
      remove: 'Remove',
    ),
    commandPalette: KunCommandPaletteStrings(
      placeholder: 'Search…',
      empty: 'Type to search',
      noResult: 'No results',
      loading: 'Loading…',
      close: 'Close',
      hintSelect: 'Select',
      hintOpen: 'Open',
      hintClose: 'Close',
      resultCount: '{count} results',
    ),
    copy: KunCopyStrings(
      copied: 'Copied',
      success: 'Copied {text}',
      failure: 'Could not copy {text} — your browser blocked clipboard access.',
    ),
    datePicker: KunDatePickerStrings(
      placeholderDay: 'Select a date',
      placeholderMonth: 'Select a month',
      placeholderYear: 'Select a year',
      clear: 'Clear',
      today: 'Today',
      close: 'Close',
      prevYear: 'Previous year',
      nextYear: 'Next year',
      prevPage: 'Previous {unit}',
      nextPage: 'Next {unit}',
      zoomOut: '{label} — zoom out',
      unitMonth: 'month',
      unitYear: 'year',
      unitDecade: 'decade',
      monthCell: '{month} {year}',
    ),
    drawer: KunDrawerStrings(
      close: 'Close drawer',
    ),
    fileInput: KunFileInputStrings(
      trigger: 'Choose files',
      selected: '{count} files selected',
    ),
    filePicker: KunFilePickerStrings(
      tooLarge: '{name} exceeds the {size} size limit',
    ),
    input: KunInputStrings(
      clear: 'Clear',
      reveal: 'Show password',
      hide: 'Hide password',
    ),
    kbd: KunKbdStrings(
      control: 'Control',
      alt: 'Alt',
      option: 'Option',
      shift: 'Shift',
      command: 'Command',
      meta: 'Windows',
      enter: 'Enter',
      escape: 'Escape',
      backspace: 'Backspace',
      delete: 'Delete',
      tab: 'Tab',
      space: 'Space',
      up: 'Up Arrow',
      down: 'Down Arrow',
      left: 'Left Arrow',
      right: 'Right Arrow',
      pageUp: 'Page Up',
      pageDown: 'Page Down',
      home: 'Home',
      end: 'End',
      plus: 'Plus',
      then: 'then',
    ),
    lightbox: KunLightboxStrings(
      label: 'Image viewer',
      close: 'Close',
      prev: 'Previous image',
      next: 'Next image',
      goto: 'Go to image {index}',
      zoomIn: 'Zoom in',
      zoomOut: 'Zoom out',
      rotateLeft: 'Rotate 90° left',
      rotateRight: 'Rotate 90° right',
      reset: 'Reset zoom, rotation and position',
      download: 'Download',
    ),
    lightboxGallery: KunLightboxGalleryStrings(
      view: 'View full size',
    ),
    loading: KunLoadingStrings(
      description: 'Loading…',
    ),
    loli: KunLoliStrings(
      close: 'Close',
    ),
    message: KunMessageStrings(
      close: 'Close',
    ),
    modal: KunModalStrings(
      close: 'Close',
    ),
    nullState: KunNullStateStrings(
      description: 'Nothing here yet',
    ),
    numberInput: KunNumberInputStrings(
      decrement: 'Decrease',
      increment: 'Increase',
    ),
    pagination: KunPaginationStrings(
      nav: 'Pagination',
      prev: 'Previous page',
      next: 'Next page',
      page: 'Page {page}',
      hintBefore: 'Use',
      hintAfter: 'to turn pages quickly',
      jumpLabel: 'Go to page',
      jump: 'Go',
    ),
    pinInput: KunPinInputStrings(
      label: 'Verification code',
      digit: '{label} digit {index}',
    ),
    reaction: KunReactionStrings(
      label: 'Like',
    ),
    select: KunSelectStrings(
      searchPlaceholder: 'Search…',
      noResult: 'No matching options',
      loading: 'Loading…',
      clear: 'Clear',
      removeOption: 'Remove {label}',
    ),
    spoiler: KunSpoilerStrings(
      copyCode: 'Copy code',
      reveal: 'Spoiler — click or press Enter to reveal',
    ),
    steps: KunStepsStrings(
      completed: 'Completed: {title}',
      current: 'Current step: {title}',
      pending: 'Not started: {title}',
      error: 'Error: {title}',
    ),
    tagInput: KunTagInputStrings(
      tag: 'Tag {tag}',
      removeTag: 'Remove tag {tag}',
    ),
    textSelection: KunTextSelectionStrings(
      copy: 'Copy',
      cut: 'Cut',
      paste: 'Paste',
      selectAll: 'Select all',
      share: 'Share',
      lookUp: 'Look Up',
      searchWeb: 'Search Web',
    ),
    upload: KunUploadStrings(
      imageAlt: 'Uploaded image',
      cropTitle: 'Crop image',
      cancel: 'Cancel',
      confirm: 'OK',
    ),
  );

  /// Every catalog this package ships, by BCP 47 code.
  static const Map<String, KunMessages> byCode = {
    'zh-CN': zhCN,
    'en': en,
  };
}
