// AUTO-GENERATED by packages/ui-core/scripts/gen-messages-flutter.mjs —
// do not edit. Source: packages/ui-core/src/locale/*.json, the same
// catalogs the web bundle resolves its strings from.

/// Every user-visible string KunUI renders on its own — accessible names
/// for icon-only controls, empty and loading states, and the handful of
/// built-in button labels.
///
/// A widget parameter that sets the same text always wins over the catalog;
/// the catalog is what the parameter falls back to.
library;

/// Strings for `KunAlert`.
class KunAlertStrings {
  const KunAlertStrings({
    required this.title,
    required this.confirm,
    required this.cancel,
  });

  /// `en`: Confirm
  final String title;

  /// `en`: OK
  final String confirm;

  /// `en`: Cancel
  final String cancel;
}

/// Strings for `KunAutocomplete`.
class KunAutocompleteStrings {
  const KunAutocompleteStrings({
    required this.clear,
    required this.loading,
    required this.noResult,
  });

  /// `en`: Clear
  final String clear;

  /// `en`: Loading…
  final String loading;

  /// `en`: No matching options
  final String noResult;
}

/// Strings for `KunAvatar`.
class KunAvatarStrings {
  const KunAvatarStrings({
    required this.unknownUser,
  });

  /// `en`: Unknown user
  final String unknownUser;
}

/// Strings for `KunAvatarGroup`.
class KunAvatarGroupStrings {
  const KunAvatarGroupStrings({
    required String label,
  }) : _label = label;

  final String _label;

  /// `en`: {count} users
  String label({required Object count}) =>
      _label.replaceAll('{count}', '$count');
}

/// Strings for `KunCarousel`.
class KunCarouselStrings {
  const KunCarouselStrings({
    required this.label,
    required this.prev,
    required this.next,
    required this.nav,
    required String goto,
  }) : _goto = goto;

  /// `en`: Carousel
  final String label;

  /// `en`: Previous slide
  final String prev;

  /// `en`: Next slide
  final String next;

  /// `en`: Carousel navigation
  final String nav;

  final String _goto;

  /// `en`: Go to slide {index}
  String goto({required Object index}) => _goto.replaceAll('{index}', '$index');
}

/// Strings for `KunChip`.
class KunChipStrings {
  const KunChipStrings({
    required this.remove,
  });

  /// `en`: Remove
  final String remove;
}

/// Strings for `KunCommandPalette`.
class KunCommandPaletteStrings {
  const KunCommandPaletteStrings({
    required this.placeholder,
    required this.empty,
    required this.noResult,
    required this.loading,
    required this.close,
    required this.hintSelect,
    required this.hintOpen,
    required this.hintClose,
    required String resultCount,
  }) : _resultCount = resultCount;

  /// `en`: Search…
  final String placeholder;

  /// `en`: Type to search
  final String empty;

  /// `en`: No results
  final String noResult;

  /// `en`: Loading…
  final String loading;

  /// `en`: Close
  final String close;

  /// `en`: Select
  final String hintSelect;

  /// `en`: Open
  final String hintOpen;

  /// `en`: Close
  final String hintClose;

  final String _resultCount;

  /// `en`: {count} results
  String resultCount({required Object count}) =>
      _resultCount.replaceAll('{count}', '$count');
}

/// Strings for `KunCopy`.
class KunCopyStrings {
  const KunCopyStrings({
    required this.copied,
    required String success,
    required String failure,
  })  : _success = success,
        _failure = failure;

  /// `en`: Copied
  final String copied;

  final String _success;

  final String _failure;

  /// `en`: Copied {text}
  String success({required Object text}) =>
      _success.replaceAll('{text}', '$text');

  /// `en`: Could not copy {text} — your browser blocked clipboard access.
  String failure({required Object text}) =>
      _failure.replaceAll('{text}', '$text');
}

/// Strings for `KunDatePicker`.
class KunDatePickerStrings {
  const KunDatePickerStrings({
    required this.placeholderDay,
    required this.placeholderMonth,
    required this.placeholderYear,
    required this.clear,
    required this.today,
    required this.close,
    required this.prevYear,
    required this.nextYear,
    required String prevPage,
    required String nextPage,
    required String zoomOut,
    required this.unitMonth,
    required this.unitYear,
    required this.unitDecade,
    required String monthCell,
  })  : _prevPage = prevPage,
        _nextPage = nextPage,
        _zoomOut = zoomOut,
        _monthCell = monthCell;

  /// `en`: Select a date
  final String placeholderDay;

  /// `en`: Select a month
  final String placeholderMonth;

  /// `en`: Select a year
  final String placeholderYear;

  /// `en`: Clear
  final String clear;

  /// `en`: Today
  final String today;

  /// `en`: Close
  final String close;

  /// `en`: Previous year
  final String prevYear;

  /// `en`: Next year
  final String nextYear;

  /// `en`: month
  final String unitMonth;

  /// `en`: year
  final String unitYear;

  /// `en`: decade
  final String unitDecade;

  final String _prevPage;

  final String _nextPage;

  final String _zoomOut;

  final String _monthCell;

  /// `en`: Previous {unit}
  String prevPage({required Object unit}) =>
      _prevPage.replaceAll('{unit}', '$unit');

  /// `en`: Next {unit}
  String nextPage({required Object unit}) =>
      _nextPage.replaceAll('{unit}', '$unit');

  /// `en`: {label} — zoom out
  String zoomOut({required Object label}) =>
      _zoomOut.replaceAll('{label}', '$label');

  /// `en`: {month} {year}
  String monthCell({required Object year, required Object month}) =>
      _monthCell.replaceAll('{year}', '$year').replaceAll('{month}', '$month');
}

/// Strings for `KunDrawer`.
class KunDrawerStrings {
  const KunDrawerStrings({
    required this.close,
  });

  /// `en`: Close drawer
  final String close;
}

/// Strings for `KunFileInput`.
class KunFileInputStrings {
  const KunFileInputStrings({
    required this.trigger,
    required String selected,
  }) : _selected = selected;

  /// `en`: Choose files
  final String trigger;

  final String _selected;

  /// `en`: {count} files selected
  String selected({required Object count}) =>
      _selected.replaceAll('{count}', '$count');
}

/// Strings for `KunFilePicker`.
class KunFilePickerStrings {
  const KunFilePickerStrings({
    required String tooLarge,
  }) : _tooLarge = tooLarge;

  final String _tooLarge;

  /// `en`: {name} exceeds the {size} size limit
  String tooLarge({required Object name, required Object size}) =>
      _tooLarge.replaceAll('{name}', '$name').replaceAll('{size}', '$size');
}

/// Strings for `KunInput`.
class KunInputStrings {
  const KunInputStrings({
    required this.clear,
    required this.reveal,
    required this.hide,
  });

  /// `en`: Clear
  final String clear;

  /// `en`: Show password
  final String reveal;

  /// `en`: Hide password
  final String hide;
}

/// Strings for `KunLightbox`.
class KunLightboxStrings {
  const KunLightboxStrings({
    required this.label,
    required this.close,
    required this.prev,
    required this.next,
    required String goto,
    required this.zoomIn,
    required this.zoomOut,
    required this.rotateLeft,
    required this.rotateRight,
    required this.reset,
    required this.download,
  }) : _goto = goto;

  /// `en`: Image viewer
  final String label;

  /// `en`: Close
  final String close;

  /// `en`: Previous image
  final String prev;

  /// `en`: Next image
  final String next;

  /// `en`: Zoom in
  final String zoomIn;

  /// `en`: Zoom out
  final String zoomOut;

  /// `en`: Rotate 90° left
  final String rotateLeft;

  /// `en`: Rotate 90° right
  final String rotateRight;

  /// `en`: Reset zoom, rotation and position
  final String reset;

  /// `en`: Download
  final String download;

  final String _goto;

  /// `en`: Go to image {index}
  String goto({required Object index}) => _goto.replaceAll('{index}', '$index');
}

/// Strings for `KunLightboxGallery`.
class KunLightboxGalleryStrings {
  const KunLightboxGalleryStrings({
    required this.view,
  });

  /// `en`: View full size
  final String view;
}

/// Strings for `KunLoading`.
class KunLoadingStrings {
  const KunLoadingStrings({
    required this.description,
  });

  /// `en`: Loading…
  final String description;
}

/// Strings for `KunLoli`.
class KunLoliStrings {
  const KunLoliStrings({
    required this.close,
  });

  /// `en`: Close
  final String close;
}

/// Strings for `KunMessage`.
class KunMessageStrings {
  const KunMessageStrings({
    required this.close,
  });

  /// `en`: Close
  final String close;
}

/// Strings for `KunModal`.
class KunModalStrings {
  const KunModalStrings({
    required this.close,
  });

  /// `en`: Close
  final String close;
}

/// Strings for `KunNullState`.
///
/// Reached as `messages.nullState`: the web namespace is
/// `null`, which is a Dart reserved word.
class KunNullStateStrings {
  const KunNullStateStrings({
    required this.description,
  });

  /// `en`: Nothing here yet
  final String description;
}

/// Strings for `KunNumberInput`.
class KunNumberInputStrings {
  const KunNumberInputStrings({
    required this.decrement,
    required this.increment,
  });

  /// `en`: Decrease
  final String decrement;

  /// `en`: Increase
  final String increment;
}

/// Strings for `KunPagination`.
class KunPaginationStrings {
  const KunPaginationStrings({
    required this.nav,
    required this.prev,
    required this.next,
    required String page,
    required this.hintBefore,
    required this.hintAfter,
    required this.jumpLabel,
    required this.jump,
  }) : _page = page;

  /// `en`: Pagination
  final String nav;

  /// `en`: Previous page
  final String prev;

  /// `en`: Next page
  final String next;

  /// `en`: Use
  final String hintBefore;

  /// `en`: to turn pages quickly
  final String hintAfter;

  /// `en`: Go to page
  final String jumpLabel;

  /// `en`: Go
  final String jump;

  final String _page;

  /// `en`: Page {page}
  String page({required Object page}) => _page.replaceAll('{page}', '$page');
}

/// Strings for `KunPinInput`.
class KunPinInputStrings {
  const KunPinInputStrings({
    required this.label,
    required String digit,
  }) : _digit = digit;

  /// `en`: Verification code
  final String label;

  final String _digit;

  /// `en`: {label} digit {index}
  String digit({required Object label, required Object index}) =>
      _digit.replaceAll('{label}', '$label').replaceAll('{index}', '$index');
}

/// Strings for `KunReaction`.
class KunReactionStrings {
  const KunReactionStrings({
    required this.label,
  });

  /// `en`: Like
  final String label;
}

/// Strings for `KunSelect`.
class KunSelectStrings {
  const KunSelectStrings({
    required this.searchPlaceholder,
    required this.noResult,
    required this.loading,
    required this.clear,
    required String removeOption,
  }) : _removeOption = removeOption;

  /// `en`: Search…
  final String searchPlaceholder;

  /// `en`: No matching options
  final String noResult;

  /// `en`: Loading…
  final String loading;

  /// `en`: Clear
  final String clear;

  final String _removeOption;

  /// `en`: Remove {label}
  String removeOption({required Object label}) =>
      _removeOption.replaceAll('{label}', '$label');
}

/// Strings for `KunSpoiler`.
class KunSpoilerStrings {
  const KunSpoilerStrings({
    required this.copyCode,
    required this.reveal,
  });

  /// `en`: Copy code
  final String copyCode;

  /// `en`: Spoiler — click or press Enter to reveal
  final String reveal;
}

/// Strings for `KunTagInput`.
class KunTagInputStrings {
  const KunTagInputStrings({
    required String tag,
    required String removeTag,
  })  : _tag = tag,
        _removeTag = removeTag;

  final String _tag;

  final String _removeTag;

  /// `en`: Tag {tag}
  String tag({required Object tag}) => _tag.replaceAll('{tag}', '$tag');

  /// `en`: Remove tag {tag}
  String removeTag({required Object tag}) =>
      _removeTag.replaceAll('{tag}', '$tag');
}

/// Strings for `KunUpload`.
class KunUploadStrings {
  const KunUploadStrings({
    required this.imageAlt,
    required this.cropTitle,
    required this.cancel,
    required this.confirm,
  });

  /// `en`: Uploaded image
  final String imageAlt;

  /// `en`: Crop image
  final String cropTitle;

  /// `en`: Cancel
  final String cancel;

  /// `en`: OK
  final String confirm;
}

/// A complete KunUI message catalog.
///
/// ```dart
/// const messages = KunMessages.zhCN;
/// Semantics(label: messages.input.clear, child: …);
/// Text(messages.pagination.page(page: 3));
/// ```
///
/// A string with a `{placeholder}` is a method with required named
/// parameters, not a field: the whole template is one string because a
/// value moves position between languages, and requiring the parameters
/// means a missing one is a compile error instead of a literal `{month}`
/// in an accessibility label.
class KunMessages {
  const KunMessages({
    required this.name,
    required this.code,
    required this.alert,
    required this.autocomplete,
    required this.avatar,
    required this.avatarGroup,
    required this.carousel,
    required this.chip,
    required this.commandPalette,
    required this.copy,
    required this.datePicker,
    required this.drawer,
    required this.fileInput,
    required this.filePicker,
    required this.input,
    required this.lightbox,
    required this.lightboxGallery,
    required this.loading,
    required this.loli,
    required this.message,
    required this.modal,
    required this.nullState,
    required this.numberInput,
    required this.pagination,
    required this.pinInput,
    required this.reaction,
    required this.select,
    required this.spoiler,
    required this.tagInput,
    required this.upload,
  });

  /// Endonym, for a language switcher's own list (e.g. `简体中文`).
  final String name;

  /// BCP 47 tag. KunUI never picks a locale for you; this is what a
  /// `KunDatePicker` resolves its calendar grid from when you do.
  final String code;

  final KunAlertStrings alert;

  final KunAutocompleteStrings autocomplete;

  final KunAvatarStrings avatar;

  final KunAvatarGroupStrings avatarGroup;

  final KunCarouselStrings carousel;

  final KunChipStrings chip;

  final KunCommandPaletteStrings commandPalette;

  final KunCopyStrings copy;

  final KunDatePickerStrings datePicker;

  final KunDrawerStrings drawer;

  final KunFileInputStrings fileInput;

  final KunFilePickerStrings filePicker;

  final KunInputStrings input;

  final KunLightboxStrings lightbox;

  final KunLightboxGalleryStrings lightboxGallery;

  final KunLoadingStrings loading;

  final KunLoliStrings loli;

  final KunMessageStrings message;

  final KunModalStrings modal;

  final KunNullStateStrings nullState;

  final KunNumberInputStrings numberInput;

  final KunPaginationStrings pagination;

  final KunPinInputStrings pinInput;

  final KunReactionStrings reaction;

  final KunSelectStrings select;

  final KunSpoilerStrings spoiler;

  final KunTagInputStrings tagInput;

  final KunUploadStrings upload;

  /// 简体中文 (`zh-CN`).
  static const KunMessages zhCN = KunMessages(
    name: '简体中文',
    code: 'zh-CN',
    alert: KunAlertStrings(
      title: '确认',
      confirm: '确定',
      cancel: '取消',
    ),
    autocomplete: KunAutocompleteStrings(
      clear: '清除',
      loading: '加载中…',
      noResult: '无匹配项',
    ),
    avatar: KunAvatarStrings(
      unknownUser: '未知用户',
    ),
    avatarGroup: KunAvatarGroupStrings(
      label: '{count} 位用户',
    ),
    carousel: KunCarouselStrings(
      label: '轮播',
      prev: '上一张',
      next: '下一张',
      nav: '轮播导航',
      goto: '跳到第 {index} 张',
    ),
    chip: KunChipStrings(
      remove: '移除',
    ),
    commandPalette: KunCommandPaletteStrings(
      placeholder: '搜索…',
      empty: '输入关键字搜索',
      noResult: '无结果',
      loading: '加载中…',
      close: '关闭',
      hintSelect: '选择',
      hintOpen: '打开',
      hintClose: '关闭',
      resultCount: '{count} 条结果',
    ),
    copy: KunCopyStrings(
      copied: '已复制',
      success: '{text} 复制成功',
      failure: '{text} 复制失败! 请更换更现代的浏览器!',
    ),
    datePicker: KunDatePickerStrings(
      placeholderDay: '请选择日期',
      placeholderMonth: '请选择月份',
      placeholderYear: '请选择年份',
      clear: '清空',
      today: '今天',
      close: '关闭',
      prevYear: '上一年',
      nextYear: '下一年',
      prevPage: '上一{unit}',
      nextPage: '下一{unit}',
      zoomOut: '{label} — 返回上一级',
      unitMonth: '月',
      unitYear: '年',
      unitDecade: '个十年',
      monthCell: '{year}年{month}',
    ),
    drawer: KunDrawerStrings(
      close: '关闭抽屉',
    ),
    fileInput: KunFileInputStrings(
      trigger: '选择文件',
      selected: '已选 {count} 个文件',
    ),
    filePicker: KunFilePickerStrings(
      tooLarge: '{name} 超过大小限制 ({size})',
    ),
    input: KunInputStrings(
      clear: '清除',
      reveal: '显示密码',
      hide: '隐藏密码',
    ),
    lightbox: KunLightboxStrings(
      label: '图片查看器',
      close: '关闭',
      prev: '上一张',
      next: '下一张',
      goto: '跳转到第 {index} 张',
      zoomIn: '放大',
      zoomOut: '缩小',
      rotateLeft: '向左旋转 90°',
      rotateRight: '向右旋转 90°',
      reset: '重置缩放/旋转/位置',
      download: '下载',
    ),
    lightboxGallery: KunLightboxGalleryStrings(
      view: '查看大图',
    ),
    loading: KunLoadingStrings(
      description: '正在摸鱼中...咕咕咕',
    ),
    loli: KunLoliStrings(
      close: '关闭',
    ),
    message: KunMessageStrings(
      close: '关闭',
    ),
    modal: KunModalStrings(
      close: '关闭',
    ),
    nullState: KunNullStateStrings(
      description: '莲说这里什么都没有',
    ),
    numberInput: KunNumberInputStrings(
      decrement: '减少',
      increment: '增加',
    ),
    pagination: KunPaginationStrings(
      nav: '分页导航',
      prev: '上一页',
      next: '下一页',
      page: '第 {page} 页',
      hintBefore: '您可以使用',
      hintAfter: '来进行快速翻页',
      jumpLabel: '跳转到页数',
      jump: '跳转',
    ),
    pinInput: KunPinInputStrings(
      label: '验证码',
      digit: '{label} 第 {index} 位',
    ),
    reaction: KunReactionStrings(
      label: '点赞',
    ),
    select: KunSelectStrings(
      searchPlaceholder: '搜索…',
      noResult: '无匹配项',
      loading: '加载中…',
      clear: '清除',
      removeOption: '移除 {label}',
    ),
    spoiler: KunSpoilerStrings(
      copyCode: '复制代码',
      reveal: '剧透内容,点击或按回车显示',
    ),
    tagInput: KunTagInputStrings(
      tag: '标签 {tag}',
      removeTag: '移除标签 {tag}',
    ),
    upload: KunUploadStrings(
      imageAlt: '上传图片',
      cropTitle: '裁剪图片',
      cancel: '取消',
      confirm: '确定',
    ),
  );

  /// English (`en`).
  static const KunMessages en = KunMessages(
    name: 'English',
    code: 'en',
    alert: KunAlertStrings(
      title: 'Confirm',
      confirm: 'OK',
      cancel: 'Cancel',
    ),
    autocomplete: KunAutocompleteStrings(
      clear: 'Clear',
      loading: 'Loading…',
      noResult: 'No matching options',
    ),
    avatar: KunAvatarStrings(
      unknownUser: 'Unknown user',
    ),
    avatarGroup: KunAvatarGroupStrings(
      label: '{count} users',
    ),
    carousel: KunCarouselStrings(
      label: 'Carousel',
      prev: 'Previous slide',
      next: 'Next slide',
      nav: 'Carousel navigation',
      goto: 'Go to slide {index}',
    ),
    chip: KunChipStrings(
      remove: 'Remove',
    ),
    commandPalette: KunCommandPaletteStrings(
      placeholder: 'Search…',
      empty: 'Type to search',
      noResult: 'No results',
      loading: 'Loading…',
      close: 'Close',
      hintSelect: 'Select',
      hintOpen: 'Open',
      hintClose: 'Close',
      resultCount: '{count} results',
    ),
    copy: KunCopyStrings(
      copied: 'Copied',
      success: 'Copied {text}',
      failure: 'Could not copy {text} — your browser blocked clipboard access.',
    ),
    datePicker: KunDatePickerStrings(
      placeholderDay: 'Select a date',
      placeholderMonth: 'Select a month',
      placeholderYear: 'Select a year',
      clear: 'Clear',
      today: 'Today',
      close: 'Close',
      prevYear: 'Previous year',
      nextYear: 'Next year',
      prevPage: 'Previous {unit}',
      nextPage: 'Next {unit}',
      zoomOut: '{label} — zoom out',
      unitMonth: 'month',
      unitYear: 'year',
      unitDecade: 'decade',
      monthCell: '{month} {year}',
    ),
    drawer: KunDrawerStrings(
      close: 'Close drawer',
    ),
    fileInput: KunFileInputStrings(
      trigger: 'Choose files',
      selected: '{count} files selected',
    ),
    filePicker: KunFilePickerStrings(
      tooLarge: '{name} exceeds the {size} size limit',
    ),
    input: KunInputStrings(
      clear: 'Clear',
      reveal: 'Show password',
      hide: 'Hide password',
    ),
    lightbox: KunLightboxStrings(
      label: 'Image viewer',
      close: 'Close',
      prev: 'Previous image',
      next: 'Next image',
      goto: 'Go to image {index}',
      zoomIn: 'Zoom in',
      zoomOut: 'Zoom out',
      rotateLeft: 'Rotate 90° left',
      rotateRight: 'Rotate 90° right',
      reset: 'Reset zoom, rotation and position',
      download: 'Download',
    ),
    lightboxGallery: KunLightboxGalleryStrings(
      view: 'View full size',
    ),
    loading: KunLoadingStrings(
      description: 'Loading…',
    ),
    loli: KunLoliStrings(
      close: 'Close',
    ),
    message: KunMessageStrings(
      close: 'Close',
    ),
    modal: KunModalStrings(
      close: 'Close',
    ),
    nullState: KunNullStateStrings(
      description: 'Nothing here yet',
    ),
    numberInput: KunNumberInputStrings(
      decrement: 'Decrease',
      increment: 'Increase',
    ),
    pagination: KunPaginationStrings(
      nav: 'Pagination',
      prev: 'Previous page',
      next: 'Next page',
      page: 'Page {page}',
      hintBefore: 'Use',
      hintAfter: 'to turn pages quickly',
      jumpLabel: 'Go to page',
      jump: 'Go',
    ),
    pinInput: KunPinInputStrings(
      label: 'Verification code',
      digit: '{label} digit {index}',
    ),
    reaction: KunReactionStrings(
      label: 'Like',
    ),
    select: KunSelectStrings(
      searchPlaceholder: 'Search…',
      noResult: 'No matching options',
      loading: 'Loading…',
      clear: 'Clear',
      removeOption: 'Remove {label}',
    ),
    spoiler: KunSpoilerStrings(
      copyCode: 'Copy code',
      reveal: 'Spoiler — click or press Enter to reveal',
    ),
    tagInput: KunTagInputStrings(
      tag: 'Tag {tag}',
      removeTag: 'Remove tag {tag}',
    ),
    upload: KunUploadStrings(
      imageAlt: 'Uploaded image',
      cropTitle: 'Crop image',
      cancel: 'Cancel',
      confirm: 'OK',
    ),
  );

  /// Every catalog this package ships, by BCP 47 code.
  static const Map<String, KunMessages> byCode = {
    'zh-CN': zhCN,
    'en': en,
  };
}
