// Publish the shared ballistic model (packages/ui-tokens/scripts/
// motion-physics.mjs) as TypeScript so KunShatter consumes the same constants
// gen-tokens.mjs emits into kun_ui_tokens' `KunShatterPhysics`. Output:
// src/motionPhysics.generated.ts (committed).
//
//   pnpm gen        (from the repo root — runs every generator in order)
//
// Two of the constants are component *prop defaults* (duration, rotation) and
// have to stay literal in Shatter.vue's withDefaults: vue-component-meta reads
// the literal, and an identifier default would put the expression text in the
// docs PropsTable instead of the number. A literal can drift, so this script
// asserts the SFC still agrees with the manifest and stops the build when it
// does not.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { SHATTER_PHYSICS } from '../../ui-tokens/scripts/motion-physics.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const sfcFile = join(here, '..', '..', 'vue', 'src', 'components', 'Shatter.vue')
const outFile = join(here, '..', 'src', 'motionPhysics.generated.ts')

const sfc = readFileSync(sfcFile, 'utf8')
const assertDefault = (prop, expected) => {
  const hits = [...sfc.matchAll(new RegExp(`^\\s*${prop}: (\\d+),$`, 'gm'))]
  if (hits.length !== 1 || Number(hits[0][1]) !== expected) {
    console.error(
      `gen-motion: Shatter.vue's withDefaults must carry \`${prop}: ${expected},\` ` +
        `exactly once (found ${hits.map((m) => m[1]).join(', ') || 'nothing'}). ` +
        'The tuned default lives in packages/ui-tokens/scripts/motion-physics.mjs — ' +
        'change it there and mirror the literal in the SFC, or restore the literal.'
    )
    process.exit(1)
  }
}
assertDefault('duration', SHATTER_PHYSICS.defaultDurationMs)
assertDefault('rotation', SHATTER_PHYSICS.defaultRotationDeg)

const body = Object.entries(SHATTER_PHYSICS)
  .map(([key, value]) => `  ${key}: ${value},`)
  .join('\n')

writeFileSync(
  outFile,
  `// AUTO-GENERATED by scripts/gen-motion.mjs from
// packages/ui-tokens/scripts/motion-physics.mjs — do not edit.

/**
 * The ballistic model behind \`KunShatter\`, as data — outward impulse, air
 * drag (\`1 − (1−t)^dragExponent\`), gravity as a t² acceleration — sampled
 * into \`keyframeSteps\` linear keyframes per shard. The same manifest
 * generates \`KunShatterPhysics\` in the kun_ui_tokens pub package, so the
 * web and Flutter renditions of the motion cannot drift. Tune the feel in
 * the manifest, never inline in a component.
 */
export const KUN_SHATTER_PHYSICS = {
${body}
} as const
`
)

console.log(
  `wrote motionPhysics.generated.ts — ${Object.keys(SHATTER_PHYSICS).length} constants, Shatter.vue defaults in agreement`
)
